dev/products/fc/ls5_fc_albers.yaml

Add munged LS5_fc product definition - should be consistent with the Landsat 5 Fractional cover that has been uploaded to AWS. (untested)

Add LS5_fc product definition

---

dev/terria/dea.json

This will make it so that the DEA ODC and GSKY layers are known to have CORS enabled so the terriajs-server proxy will not be used.
It will also give a reasonable home camera view on load.

Add in CORS domains and a reasonable home camera over Australia.

---

dev/terria/dea.json

Not all GA layers are CORS enabled so being more specific ensures non-DEA layers will go via the proxy.
Make the GSKY Prod URL use HTTPS - otherwise when accessing Terria-Cube on HTTPS but GSKY on HTTP the proxy is used.

Tweak DEA CORS domain. Make GSKY Prod use TLS.

---

dev/services/wms/ows/wms_cfg.py

On higher level zoom factor, if the dataset is derived from `landsat7`  issues with overviews

Decrease the zoom level for wofls layer

---

dev/services/wms/ows/wms_cfg.py

RBT identified an issue with nidem clipping extreme tides, this change ensures those tides are rendered in the WMS.

Remove clipping on Nidem below -2.5

---

dev/services/wms/thredds/wms_cfg.py

Because NBR is meant to be used to compare two sets of data all of the interesting bits were <0, this PR flips it and makes all of the interesting bits red.

Flip it and simplify the color scheme

---

dev/services/wms/ows/wms_cfg.py

Remove linefeeds from preformatted text in ASTER metadata as it causes a font change in terria. There seems to be some subtle difference in terriajs between how catalogue entries are rendered depending on how they are added.

Remove linefeeds from preformatted text in ASTER metadata

---

dev/services/wms/ows/wms_cfg.py

Updated Confidence layer units 'metres' to 'NDWI standard Deviation'
Copied legend png from GSKY for Relative layer

update legends for ITEM to match as GSKY

---

dev/terria/dea.json

This is to support TerriaJS's new feature that allows a layers times to be filtered to only those times for which the data covers a selected point. The `featureTimesProperty` property tells TerriaJS the name of the feature info property that indicates the availability times.
We're in the process of deploying a new Terria Cube that has this new feature, but it won't break anything to include this property in the meantime.

Add featureTimesProperty to layers that support it

---

dev/terria/dea.json

Wetland polygons not working when accessed from http://terria-cube.terria.io/ instead of https

Use https to avoid CORS errors

---

dev/services/wms/ows/wms_cfg.py

Our new infrastructure uses a different service url *.services.dev.dea.ga.gov.au

add eks url to wms config

---

dev/products/bare-earth/summary/be-ls-combined-product-definition.yaml

Add new product definition for `landsat_barest_earth` combined product (Landsat_5, Landsat7, and Landsat_8)

Add new product definition for landsat_barest_earth

---

dev/services/wms/ows/wms_cfg.py

NDCI is currently masked using 
```
(data["nbart_red_edge_1"] - data["nbart_red"]) / (data["nbart_red_edge_1"] + data["nbart_red"]).where(((data["nbart_green"] - data["nbart_swir_3"]) / (data["nbart_green"] + data["nbart_swir_3"])) > 0.1)
```
This uses "nbart_swir_3", when it should use "nbart_swir_2". Have updated this to:
```
(data["nbart_red_edge_1"] - data["nbart_red"]) / (data["nbart_red_edge_1"] + data["nbart_red"]).where(((data["nbart_green"] - data["nbart_swir_2"]) / (data["nbart_green"] + data["nbart_swir_2"])) > 0.1)
```

Fix incorrect MNDWI band for NDCI mask

---

dev/services/wms/ows/wms_cfg.py

This will:
Ensure WCS works correctly with these layers, 
Ensure Set the default CRS that WCS will use when downloading these layers
Clean up our logs
It will hopefully improve getCaps performance too.

Add default wcs crs to products that were missing it

---

dev/terria/dea.json

This PR updates the styling of charts so that availability of imagery is now plotted as dots along a line.
Don't merge until TerriaCube has been updated to the latest version of TerriaJS.

Update chart presentation

---

dev/services/wms/ows/wms_cfg.py
dev/terria/dea.json

- Correct style layer names
- Group Landsat-8 Barest Earth and Landsat 30+ Barest Earth to one group
- Add Barest Earth to Dev

Add barest earth to dev

---

dev/terria/dea-maps.json

This catalog is intended for maps.dea.ga.gov.au - it should only include DEA products from GSKY and our production stack. The order is intended to encourage easier traversal of our services, however some decisions are bound to be controversial so this should expect to change a bit as we receive feedback.

Add new dea-maps catalog

---

dev/terria/dea-maps.json

- As title says, release barest earth 30years to `Digital Earth Australia Terria Map` (`http://de-australia.terria.io/`)

Release barest earth 30yr to Digital Earth Australia Terria Map

---

dev/terria/dea.json

NCI have released a new endpoint, replacing our Landsat collection 2 with Landsat collection 3. One point of improvement is that the "valid data polygon" should be more accurate, so data available for dates should work better.

Add Collection 3 beta layer

---

dev/services/wms/ows/ows_cfg.py

Make sentinel 2 definitive pull ranges from the database instead of caching it.
- Combined s2a / s2b
- s2a
- s2b
We're regularly indexing datasets from thredds, which means the temporal ranges are changing each day. If a layer isn't marked as dynamic it will only update the temporal ranges when pods are restarted. This can cause some issues when we scale up as newer servers will report updated ranges, and older servers won't know how to honour them. The fix is to pull ranges from the database for these products that change often.
This change will affect dev, if successful we can roll a similar change to production.

Make sentinel 2 definitive pull ranges from the database instead of caching it

---

dev/services/wms/ows/ows_cfg.py

As ows will cache temporal extents on startup, things that are updated daily should be configured to be dynamic (pull temporal extents from database) - otherwise we get into an awkward state when newer ows pods have different extents to the older ones, especially a problem when we have autoscaled. 
This change ensures that all products that are updated daily are set to dynamic
- S2 Definitive a, b, a+b (already set)
- S2 NRT a, b, a+b (already set)
- FC L7, L8 5+7+8 
- WOFL 
N.B. I intentionally didn't set dynamic on FC L5 as it is not being produced daily. Enabling dynamic increases load on the DB and performance of getCaps so we should use it sparingly.

configure fc and wofs daily products to be dynamic

---

prod/services/wms/ows/ows_cfg.py

Testing for change #538 was successful, this change is to roll those changes out to the production environment. 
I did uncover some separate bugs unrelated to this change, that will be solved in future work
- missing .tif files in ls7 fractional cover
- fc multiproduct isn't being frequently updated

Configure fc 7,8,combined and wofs_albers to be dynamic

---

prod/services/wms/ows/ows_cfg.py

Add band name as first band alias for Landsat and Sentinel 2 bands to restore expected functionality of [](https://github.com/GeoscienceAustralia/dea-config/issues/558)

Add band name as first band alias to LS and S2

---

dev/terria/dea-maps.json

This PR restores the Coastlines config so that it will be included in the DEA Maps catalogue in preparation for the product release.

Restore Coastlines config in preparation for product release

---

products/nrt/sentinel/s2_nrt.products.yaml

following the discussion from sprint planning, s2 nrt products will continue to use its current name.

rename s2 nrt products

---

dev/services/wms/ows/ows_cfg.py

VicGrid CRS alias for DELWP Geocortex support.
See https://github.com/opendatacube/datacube-ows/issues/333

Add WIKID:102171 as alias for EPSG:3111 for DELWP.

---

dev/services/wms/ows/ows_cfg.py

For https://github.com/opendatacube/datacube-ows/pull/454
Should be OK to merge BEFORE the OWS PR is merged.

Support VicGrid tile matrix set. 

---

.github/ISSUE_TEMPLATE/general-issue-template.md

by adding an issue template, the default gets overwritten, add it back. 
issue templates are in this folder, https://github.com/GeoscienceAustralia/dea-config/tree/master/.github/ISSUE_TEMPLATE
under different file names/

add general issue template

---

dev/services/alchemist/s2_nrt_wo/s2_nrt_wo.alchemist.yaml

Adds `dea_s2_derivative` naming conventions to S2 NRT WO which should merge s2a and s2b,

Update s2_nrt_wo.alchemist.yaml with naming conventions

---

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py

Landsat 7 and Landsat 8 both have Pancromatic (Pan) bands, but they are very different,
Landsat 7 spans green, red and nir bands while Landsat 8 spans blue, green and red. Just updating their style (presentation title/name) to reflect that

Differentiate Landsat 7 Pan band from Landsat 8

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/c3/ows_c3_cfg.py

test c3 nbr

---

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
dev/services/wms/ows_refactored/c3/style_c3_cfg.py

Apply geodata sea-masking to C3 Landsat NDVI and NBR styles, as discussed in this morning's C3 meeting.

Mask sea from C3 LS ndvi and nbr styles with geodata.

---

dev/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py

Mostly using the water_observed bit instead of the enumeration-like wet/dry values.
Also explicitly make nodata transparent.

Fix logic issues in C3 WOFS Observations colour map

---

dev/terria/dea-maps.json

This PR adds the updated DEA Coastlines config to the current version 7 of Terria on DEA Maps. This is a backup in case version 8 of Terria is not stood up prior to tomorrow's release.
@GypsyBojangles @pindge If you get a chance, it would be great if this PR could be reviewed as a priority so we have time to verify it works correctly. Thankyou!

Add updated DEA Coastlines config as backup option for release

---

dev/services/wms/ows_refactored/c3/style_c3_cfg.py

This implements the evenly-spaced value colour scheme I suggested on Slack for fmask:
#464633 Shadow
#475B74 Water
#84A278 Clear
#D0CFCE Cloud
#E0EDFF Snow

Updated fmask style for easier viewing

---

dev/services/wms/ows_refactored/c3/style_c3_cfg.py

Uses MPL RdYlBu ramp, from -1 to 1 for all three styles - we may want to revisit that.
Will probably also require some Terria catalog changes so the UI knows which styles support delta.

Delta styles for C3 NDVI, NDWI and MNDWI.

---

dev/terria/dea-maps-v8.json

This is a quick edit to restore the DEA Maps Terria V8 config's sharekeys to their original values. This will ensure that the catalogue change does not break previous share links.
I've tested the updated config and it works correctly on DEA Maps.

Revert Terria v8 config sharekeys in prep for C3 layers

---

products/fc/ls5_fc_albers.yaml
products/fc/ls7_fc_albers.yaml
products/fc/ls8_fc_albers.yaml

The (gridded) Landsat Fractional Cover product definitions are missing the `tile_size` information. This info is available for example in a very similar [wofs](https://github.com/GeoscienceAustralia/dea-config/blob/master/products/wofs/wofs_summary.yaml) definition.
This has recently popped us disguised as a WPS bug
- https://github.com/opendatacube/datacube-wps/issues/111
- https://github.com/opendatacube/datacube-core/issues/1152
My personal preference is to also relax `GridSpec` object construction in core, but that's not to say that these product definitions are not incomplete.

set tile_size for ls[]_fc_albers products

---

dev/services/alchemist/s2_nrt_bs/s2_c3_nrt_ba_provisional.alchemist.yaml

Removed platform property due to the below error.
```
2021-09-03 05:20:20 [info     ] Loaded and transformed         task=UUID('6438c322-412b-4e41-b1a7-435e5e07b91d')
/usr/local/lib/python3.8/dist-packages/eodatasets3/properties.py:431: PropertyOverrideWarning: Overriding property 'sentinel:datatake_start_datetime' (from '2021-09-02 03:36:20Z' to datetime.datetime(2021, 9, 2, 3, 36, 20, tzinfo=datetime.timezone.utc))
warnings.warn(message, category=PropertyOverrideWarning)
/usr/local/lib/python3.8/dist-packages/eodatasets3/properties.py:431: PropertyOverrideWarning: Overriding property 'eo:platform' (from 'sentinel-2b' to 'sentinel-2')
warnings.warn(message, category=PropertyOverrideWarning)
/usr/local/lib/python3.8/dist-packages/datacube/utils/geometry/_base.py:305: DeprecationWarning: …
```

Resolve error with output platform field

---

dev/terria/dea-maps-v8.json
dev/terria/terria-cube-v8.json

- Add provisional ARD products (Landsat combined, Sentinel-2 combined, Landsat 7 and 8, Sentinel-2 A and B) in DEA maps.
🚀

Provisional ARD in DEA maps

---

dev/terria/terria-cube-v8.json

This PR makes a number of minor updates to the dev and prod sections of the Terria config to align better with the "High Level Abstraction of Product Shortname" and "Science team proposed short names" from the ["Naming Conventions - Collection Upgrade"](https://geoscienceau.sharepoint.com/:x:/s/DEACoreTeam/EZitMQ3nZRRBrY9kLM4YFsIBVjpsRBalyCGfDODN3DC7NQ?e=dtpFa8) spreadsheet.
Key changes include:
- "DEA Surface Reflectance Geomedian (Landsat)" is now "DEA Surface Reflectance Calendar Year (Landsat)" (as per spreadsheet)
- "DEA Mangrove Canopy Cover" is now "DEA Mangroves (Landsat)" (as per spreadsheet)
- "Landsat 30+ Barest Earth Satellite Images (Combined Landsat)" is now  "GA Barest Earth (Landsat)" (as per spreadsheet)
- "DEA Land Cover (Landsat)" is now "DEA Land Cover Calendar Year …

Update Terria config to better align with naming conventions

---

dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_cyear_3 .yaml
dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_fyear_3.yaml

The FC Percentiles has two products.
1) Fractional Cover Percentiles Calendar Year (Landsat) -> ga_ls_fc_pc_cyear_3
2) Fractional Cover Percentiles Financial Year (Landsat) -> ga_ls_fc_pc_fyear_3
Therefore, we have two different config files to run odc-stats.

Update the FCP config files

---

dev/terria/dea-maps-v8.json

This PR implments the changes made on Terria Cube in #855 on DEA Maps.
From the look of it, this PR also adds in recent changes to make sure annual products are formatted in `"dateFormat": "'Year: 'yyyy",`.
(again, the re-ordering has made the diff hard to read, but the config has been tested working on DEA Maps).

Update DEA Maps with Terria changes

---

dev/terria/dea-maps-v8.json
dev/terria/terria-cube-v8.json

Two very minor consistency updates to the two Terria catalogues based on OWS:
- Change "Near Real Time" to "Near Real-Time"
- Change "DEA Low Tide Imagery" and "DEA High Tide Imagery" to "DEA Low Tide Imagery (Landsat)" and "DEA High Tide Imagery (Landsat)"

Very minor consistency updates coming back from OWS

---

check-product-definitions.sh
products/land_and_vegetation/fractional-cover/ga_ls_fc_pc_cyear_3.yaml

Previous version of FCP product definition was hastily included last week and broke CI.
This fixes #878

Fix FCP QA flag definition

---

dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_apr_oct_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_cyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_fyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_myear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_nov_mar_3.yaml

Based on Simon's feedback. Fix:
1. copy short names from product doc to config files
2. update calendar year product name from: `ga_ls_fq_cyear_3` to `ga_ls_wo_fq_cyear_3`
3. remove all rgba sections in config files. Then no rgba.tif as output in WO Summary

Update wo summary product names

---

dev/services/odc-stats/geomedian/ga_ls8c_nbart_gm_cyear_3.yaml

Remove the rgba section in Geomedian config. The `opendatacube/datacube-statistician:0.3.42` will not generate rgba.tif as output file.

Remove the rgba section, no rgba.tif as output

---

dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_cyear_3.yaml
dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_fyear_3.yaml
dev/services/odc-stats/geomedian/ga_ls8c_nbart_gm_cyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_apr_oct_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_cyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_fyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_myear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_nov_mar_3.yaml

Add four fields from the landsat namespace to skip list. The following fileds will not in odc-stats output metadata files anymore.
```
- landsat:collection_category
- landsat:collection_number
- landsat:wrs_path
- landsat:wrs_row
```

Skip more landsat properties in output dataset

---

dev/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py
dev/services/wms/ows_refactored/baseline_satellite_data/ows_category_root_cfg.py
dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_s2_cfg.py

This PR moves the two provisional combined layers into the subfolders "DEA Surface Reflectance (Landsat)" and "DEA Surface Reflectance (Sentinel-2)" for consistency with Terria Cube and DEA Maps.
@pindge Please let me know if I have done particularly the Landsat one correctly!

Relocate provisional to subfolders for consistency with DEA Maps

---

dev/terria/README.md

This PR updates the Terria instructions to point to the latest catalogue versions, and provide instructions on recommended workflows (e.g. edit Terria Cube first > DEA Maps).
Should we also rename the old Terria version 7 config files to make it clear they are no longer used? e.g. add a "_archived" or "_superseded" suffix?

Add updated terria config instructions to readme

---

products/inland_water/c3_tc/ga_ls_tc_pc_cyear_3.yaml

Tasseled cap index percentile product definition, internal only for mangroves
- Currently it has only wetness, save expansion to later brightness and greenness if we decide to release it as a product 
- change band name `tcw_pc_xx`  of `C2` to `wet_pc_xx` so that we can have `green_pc_xx` or `bright_pc_xx`

add tasseled cap index percentile product definition

---

dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_apr_oct_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_cyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_fyear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_myear_3.yaml
dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_nov_mar_3.yaml

The previous value `DEA Water Observations (WOfS)` does not follow the common pattern: `an identifier (alphanumeric with underscores, typically lowercase`. Then reuse the `ga_ls_wo_3` family name value [wo](https://github.com/GeoscienceAustralia/dea-config/blob/master/prod/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml#L43).

Change wo family name to meet expected pattern

---

dev/services/alchemist/s2_nrt_wo/s2_nrt_wo.alchemist.yaml

Change s2 nrt product back to s2c2, as assumption about updating nrt s2 wo from c2 (s2*_nrt_granule) to c3 (ga_s2*m_ard_provisional_3) was incorrect. Not just as easy as changing product name.

change s2 product back to c2 for wo config

---

products/inland_water/wofs/ga_ls_wo_fq_apr_oct_3.yaml
products/inland_water/wofs/ga_ls_wo_fq_nov_mar_3.yaml

When we add the WO seasonal summary, eventually I modify the existing C2 ones. Then the metadata_type still referece to the C2 style.
In this PR, we update the two WO seasonal summary metadata_type to C3 style (e.g. C3 cyear one https://github.com/GeoscienceAustralia/dea-config/blob/master/products/inland_water/wofs/ga_ls_wo_fq_cyear_3.yaml#L3.)

Fix wo seaonal summary metadata type

---

dev/services/wms/ows_refactored/ows_reslim_cfg.py

WCS requests were previously unrestricted, which means that a large WCS request would time out and eventually crash the pod instead of failing immediately with a useful error message.
The following restrictions now apply to all WCS requests:
1) Limit on the size of the uncompressed data to 800Mb.
2) Limit on the total number of dataset file accessed to 30.

Add sensible WCS resource limits.

---

dev/services/wms/ows_refactored/ows_reslim_cfg.py

Was 30, which resulted in ~40s queries.  Reducing to 24.

Reduce WCS dataset limit slightly

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_c3_fc_cfg.py
dev/services/wms/ows_refactored/land_and_vegetation/fc/style_fc_cfg.py

Fix masked styles to mask out all data where no QA is available from WOFS.
Added unmasked styles for review and assessment - may be removed, or may be made selectively available in some Terria instances.
(for Collection 3 Landsat FC in dev only.)
Requires code changes from https://github.com/opendatacube/datacube-ows/pull/772 to work correctly.

FC C3 masking overhaul in dev.

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_c3_fc_cfg.py
dev/services/wms/ows_refactored/land_and_vegetation/fc/style_fc_cfg.py

Unmasked styles are
*    useful for internal debugging of situations where there is a difference in extent between FC and WOFS or other issues with masking; and
*   could potentially be of interest to some external power-users; but
*    potentially for confusing amongst non-expert users.
We are therefore adding them permanently to dev, and leaving them permanently out of prod.
This applies the rest of this policy to FC C3 and is exemplar for refactoring all[1] masked styles going forward.
[1] If the only masking is sea masking, it's not really worth it - this is why I haven't done e.g. the annual and seasonal wofs layers in this PR.

Add dev-only unmasked styles to FC C3

---

prod/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml

- Add an extra group of coefficients on ls8 
- fix small error on preview thumbnail
Open to the change of coefficients name.
See https://github.com/GeoscienceAustralia/fc/pull/48 for more context on the new set of coefficients.

Fix LS8 Fractional Cover Alchemist Configuration

---

products/land_and_vegetation/lccs/lc_ls_c2.odc-product.yaml

Adding the expected gridding into the Landcover Product definition should make it look prettier in Explorer.
Please confirm that Landcover uses the same tiling configuration as the Collection 2 Albers products.

Make Landcover Extents Prettier in Explorer

---

dev/services/wms/ows_refactored/ows_reslim_cfg.py

1. S2 NRT was set to min_zoom_factor of 6.9, which is insane.  The intention was clearly min_zoom_level of 6.9, which I think is reasonable.
2. min_zoom_level has a "smart" implementation to automatically adjust for factors like native resolution, number (and size) of bands, etc.  So a single min_zoom_level value should suffice for most (if not all) layers.  I've therefore moved almost everything over to share a min_zoom_level of 6.9.
3. I've NOT included the HAP prototype layer because it really is a special case.
4. This is dev only.  I'll do some tests and profiling after this is deployed, and if I'm happy, I'll simplify by reducing the number of (now identical) resource limit definitions, then promote to prod.

Switch most dev wms resource limits to adjusted zoom level

---

dev/services/wms/ows_refactored/others/ows_mstp_cfg.py
dev/services/wms/ows_refactored/ows_reslim_cfg.py

Standard resource limit doesn't work well.  Looks like MSTP is divvied up into files (datasets) using standard grid boundaries, despite being much lower resolution.  As a result the zoom-level-adjustment calculation doesn't scale right.

Resource limit tuning for MSTP (dev only for now)

---

prod/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml

We whoopsed in December by merging a configuration change to Fractional
Cover which performs corrections on the output values of Landsat
8 FC. The whoops is because the code hasn't yet been released yet, and
so LS8 FC has been failing since then!

Fix Collection 3 Fractional Cover

---

prod/services/wms/ows_refactored/ows_reslim_cfg.py

The resource_limit in prod for Sentinel-2 products was using "min_zoom_factor" instead of "min_zoom_level" resulting in ridiculously expensive queries being attempted, with timeouts and crashes resulting.
This should fix.

Fix zoom_factor/zoom_level typo in reslims.

---

.github/workflows/terria_linting.yaml
dev/terria/terria-cube-v8.json

closes #1072 
behaviours
```
dev/terria/terria-cube-v[8]json:1077:				    "legends": [
dev/terria/terria-cube-v8.json:1080:					    "imageScaling": 0.5
dev/terria/terria-cube-v8.json:1082:				    ],
dev/terria/terria-cube-v8.json:10[9]7:				    "legends": [
dev/terria/terria-cube-v8.json:1[10]0:					    "imageScaling": 0.5
dev/terria/terria-cube-v8.json:[11]02:				    ],
Please replace tab with white spaces as per the lines indicated
```

add tab detector for terria lint

---

dev/services/odc-stats/geomedian/ga_ls8c_nbart_gm_cyear_3.yaml

Update LS8 Geomedian config to add `apply_eodatasets3` flag to match the LS7 config:
https://github.com/GeoscienceAustralia/dea-config/blob/95a2f7ea4c5f380234c752e828492987edc8a544/dev/services/odc-stats/geomedian/ga_ls7e_nbart_gm_cyear_3.yaml#L75

Add apply_eodatasets3 flag to LS8 Geomedian

---

dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py
dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py
dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py
dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_extents_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_national_cfg.py
dev/terria/dea-maps-v8.json
dev/terria/terria-cube-v8.json
prod/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py
prod/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py
prod/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py
prod/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py
prod/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_extents_cfg.py
prod/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_national_cfg.py

This PR makes two updates to our DEA Maps/Terria catalogues, and our dev/prod OWS catalogues:
- Update coastal products to follow naming convention by including "(Landsat)" after name instead of legacy acronym (agreement was to use legacy acronym is used in the folder above instead)
- I also noticed that we never updated the Collection 3 WO layers to follow the naming convention. I've updated these on dev and prod to match [the naming convention spreadsheet](https://geoscienceau.sharepoint.com/:x:/r/sites/DEACoreTeam/Shared%20Documents/Project%20Management%20Documents/Naming%20Conventions%20-%20Collection%20Upgrade.xlsx?d=w0d31ad9865e74114ad8f642cce1816c2&csf=1&web=1&e=Wndd90) and [the names on DEA Maps/Terria](https://maps.dea.ga.gov.au/#share=s-rclc5DHBcQxhZNja2mToUMf7bZ5)
e.g.
> …

Naming convention updates to Terria and OWS catalogues

---

dev/services/odc-stats/mangroves/ga_ls_mangrove_cover_fyear_3.yaml

Current odc-stats doesn't expect dynamic config. Was fixed in https://github.com/opendatacube/odc-stats/pull/54. Changing odc-stats config until that PR gets merged.
```
Stream closed EOF for processing/mangroves-fy-2010-1244291362 (wait)
wait time="2022-06-26T13:22:35.461Z" level=info msg="Main container completed"
wait time="2022-06-26T13:22:35.461Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
wait time="2022-06-26T13:22:35.461Z" level=info msg="Saving logs"
wait time="2022-06-26T13:22:35.462Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: mangroves-fy-2010/mangroves-fy-2010-1244291362/main.log"
wait time="2022-06-26T13:22:35.462Z" level=info msg="Creating minio client using static credentials" …
```

Add default empty plugin_config for mangroves odc-stats config

---

dev/terria/terria-cube-v8.json

This PR adds a featureinfo popup for the DEA Intertidal Elevation product in prep for a workshop tomorrow. If this works I'll update DEA Maps.

Minor updates to Coastal products for workshop tomorrow

---

dev/terria/dea-maps-v8.json
dev/terria/terria-cube-v8.json

This PR makes three changes:
1. Adds a featureinfo popup to the DEA Intertidal Elevation layer after testing on TerriaCube
2. Fixes featureinfo popup being added to the wrong layer on TerriaCube
3. Adds "DEA Shapes" folder from TerriaCube dev to DEA Maps

Add feature info to DEA Intertidal Elevation, add shapes

---

dev/terria/dea-maps-v8.json

- http://services.ga.gov.au/gis/services/Geomorphology_Smartline/MapServer/WMSServer
- http://services.ga.gov.au/gis/services/Australian_Coastal_Sediment_Compartments/MapServer/WMSServer
These both advertise `GetFeatureInfo` supports `text/html` format, but both return gibberish
Example `GetFeatureInfo` request with `info_format=text/html`
- http://services.ga.gov.au/gis/services/Australian_Coastal_Sediment_Compartments/MapServer/WMSServer?exceptions=XML&version=1.3.0&feature_count=101&crs=EPSG%3A3857&styles=default&service=WMS&request=GetFeatureInfo&layers=Primary_compartments&bbox=13775786.985667605%2C-2504688.542848654%2C15028131.257091936%2C-1252344.271424327&width=256&height=256&query_layers=Primary_compartments&info_format=text%2Fhtml&i=45&j=65
This PR changes `info_format=text/xml` …

Set getFeatureInfoFormat to `xml` for problematic WMS servers

---

products/baseline_satellite_data/c3/ga_ls9c_ard_3.ord-product.yaml

Adding `ga_ls9c_ard_3` ODC product definition.
Synced from [digitalearthau repo](https://github.com/GeoscienceAustralia/digitalearthau/blob/develop/digitalearthau/config/eo3/products-aws/ard_ls9.odc-product.yaml).

Add ga_ls9c_ard_3

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/baseline_satellite_data/landsat/style_c3_cfg.py

This PR adds the panchromatic true colour style to Landsat 7, and makes some minor updates to use a more logical order for the styles (panchromatic true colour next to true colour, bands in order of band number).

Add pansharpened style to Landsat 7

---

dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/band_s2_cfg.py
dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_c3_cfg.py
dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/style_s2_cfg.py

This fixes the issue when running `datacube-ows-update` - it seems to not pick up the alias `s2cloudless_mask` for flag bands.
```
Could not load layer DEA Surface Reflectance (Sentinel-2 MSI) Collection 3: Unknown band: s2cloudless_mask in layer ga_s2m_ard_3
Could not load layer DEA Surface Reflectance (Sentinel-2A MSI) Collection 3: Unknown band: s2cloudless_mask in layer ga_s2am_ard_3
Could not load layer DEA Surface Reflectance (Sentinel-2B MSI) Collection 3: Unknown band: s2cloudless_mask in layer ga_s2bm_ard_3
```
So use the primary band name of `oa_s2cloudless_mask` instead.

Use primary band name for s2cloudless_mask OWS layers

---

prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/band_s2_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_c3_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/style_s2_cfg.py

This fixes the issue when running `datacube-ows-update` - it seems to not pick up the alias `s2cloudless_mask` for flag bands.
```
Could not load layer DEA Surface Reflectance (Sentinel-2 MSI) Collection 3: Unknown band: s2cloudless_mask in layer ga_s2m_ard_3
Could not load layer DEA Surface Reflectance (Sentinel-2A MSI) Collection 3: Unknown band: s2cloudless_mask in layer ga_s2am_ard_3
Could not load layer DEA Surface Reflectance (Sentinel-2B MSI) Collection 3: Unknown band: s2cloudless_mask in layer ga_s2bm_ard_3
```
So use the primary band name of `oa_s2cloudless_mask` instead.
(equivalent PR for dev: https://github.com/GeoscienceAustralia/dea-config/pull/1115)

Use oa_s2cloudless_mask for flag bands

---

dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py
dev/terria/dea-maps-v8.json
dev/terria/terria-cube-v8.json
prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py

Now that we have only Collection 3 Sentinel-2 data available, we can remove the "Collection 3" suffix from our catalogues. This will make the data less confusing to users who are unlikely to care about the collection the data comes from.
Also swapped the DEA Maps combined Sentinel-2 ID to the older "definitive" vs "near real time" so that old share links are less likely to break.

Remove C3 suffix from S2 data in OWS and Terria

---

dev/terria/terria-cube-v8.json

I am not too familiar with how terriacube works - please let me know if something needs changing. I have removed sentinel 2 collection 1 products from the 'DEA Production' section and replaced with collection 3 leaving the same ids.

remove sentinel collection 1 and add collection 3 into terriacube in dev

---

prod/services/wms/ows_refactored/ows_reslim_cfg.py
prod/services/wms/ows_refactored/ows_root_cfg.py

At the moment, approximately none (0.44% in the last 30 days) of our OWS traffic is being cached by CloudFront. This is a problem for two reasons. 1: poor performance for OWS Users. 2: Increased load on OWS Application Servers.
This change allows GetCapabilities requests to be cached for 1 hour, and allows GetMaps/GetTile requests to be cached for 1 hour.
Previously, the only requests being cached are those for GetMap/GetTile requests that combine 4 or more datasets.

Allow Caching of OWS Responses

---

products/others/srtm/ga_srtm_dem1sv1_0.odc-product.yaml

Issue #1348 (https://github.com/opendatacube/datacube-core/issues/1348) discusses issues with the nodata value in the `ga_srtm_dem1sv1_0` SRTM DEM product. It appears that the issue is caused by the nodata value being truncated and losing precision when converted to scientific notation format, which then prevents it from being applied correctly by funcs like `from datacube.utils.masking import mask_invalid_data`. 
This PR attempts to fix this issue by using the full non-truncated nodata string instead of the shorter scientific notation.

Fix nodata value in `ga_srtm_dem1sv1_0` product

---

dev/terria/terria-cube-v8.json

This PR adds the new combined Sentinel-2 and Landsat OWS layer to Terriacube. I've added an "OWS" suffix to this layer, and an "GSKY" suffix to the old layer. 
For now I've left the FeatureInfoTemplate to use the Landsat feature info template, but this currently only includes the RGB Landsat bands that are currently included in the product. I expect this will work better once we add the other bands, but we should remember to have a look at it later on.

Add new combined S2 and Landsat layer to Terriacube

---

dev/services/wms/ows_refactored/ows_reslim_cfg.py
dev/services/wms/ows_refactored/ows_root_cfg.py
prod/services/wms/ows_refactored/ows_reslim_cfg.py

My attempt last week to enable caching failed, see https://github.com/opendatacube/datacube-ows/issues/921
I think I know what went wrong, there was no `max_datasets` set for the layers, and the caching logic decided not to cache anything.
I'm not 100% sure what a reasonable `max_datasets` is, so I've copied the value of 24 from the WCS config.
This change is against DEA Dev OWS, if it's successful, we can make it for Prod too.

Test out OWS GetMap/GetTile caching in DEA Dev OWS

---

dev/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py
dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py

I noticed that the current Sentinel-2 OWS layers haven't been updated to their Collection 3 descriptions. This PR updates these layers to use the convention agreed upon in 3/09/2021:
The new content is taken directly from CMI as per the convention, and I've updated some of the CMI URLs to point to the new product descriptions instead of the old Sentinel-2 Collection 1 data. 
Also linked to the relevant CMI listings on the Combined layers so that users can access more info about those products.

Minor Sentinel-2 Collection 3 OWS name and description updates

---

prod/services/wms/inventory.json
prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/style_combined_cfg.py

For prod.  (Dev is not appropriate for testing as it has minimal S2C3 data - combined layer has not yet been added to Terria config, so should be invisible to users.)
Adds common NIR and SWIR bands, and styles that used them.  Based closely on existing LS5 config.
I've removed references to exact central wavelengths as they vary slightly from detector to detector and platform to platform.  I've given rounded off "approximate" wavelengths instead.

IR bands for LS/S2 combined layer.

---

dev/services/wms/ows_refactored/land_and_vegetation/fc/style_fc_cfg.py
prod/services/wms/ows_refactored/land_and_vegetation/fc/style_fc_cfg.py

Daily Fractional Cover was not being displayed when the corresponding WOFS daily data was not available for masking.
This was reported as an issue against OWS: https://github.com/opendatacube/datacube-ows/issues/925
But it turns out to be an over-zealous masking rule here.
As discussed in the comments, masking by a masking product's "nodata" flag is almost certainly never the right thing to do.

Remove "nodata" flag from FC WOFS masking.

---

dev/terria/terria-cube-v8.json
prod/terria/dea-maps-v8.json

The DEA Tasseled Cap Indices Percentiles Calendar Year (Landsat) product currently uses full date strings for each timestep:
This PR formats these dates as years for consistency with all our other annual products:

Use year format for Tasseled Cap Indices Calendar Year

---

dev/terria/terria-cube-v8.json

I often find myself wanting to quickly inspect the 48 km and 32 km coastal grids for DEA Coastlines or DEA Intertidal (e.g. to choose what tile to run). This adds those grids to dev Terria so it's easier to inspect them using Terria! 😃 
Should appear under "DEA Development > Other > DEA Shapes"

Add 48 km and 32 km coastal grids to dev Terria

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_national_cfg.py

This PR removes our older NIDEM style, replacing it with two cleaner micro and macrotidal styles based on matplotlib colormaps.
This is only implemented on dev OWS as an experiment to see if it will be a suitable approach for visualising the new Collection 3 DEA Intertidal Elevation product.

Remove original NIDEM style and update micro and macrotidal styles on dev

---

dev/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py
dev/terria/terria-cube-v8.json
prod/services/wms/inventory.json
prod/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py
prod/terria/dea-maps-v8.json

Releasing Landsat 9 web service into production and addition to DEA Maps. 
DO NOT MERGE until the below tasks are complete:
Once this PR is merged - the following file will need to be updated with the Landsat 9 product id to include in OWS and Explorer updates
https://bitbucket.org/geoscienceaustralia/dea-airflow/src/master/dags/webapp_update/update_list.py

add ls9 web services to prod

---

dev/terria/terria-cube-v8.json
prod/terria/dea-maps-v8.json

This PR:
- Removes any CMI references from our Terria catalogues (affecting DEA Wetlands Insight Tool, DEA Coastlines and DEA Intertidal), replacing them with Knowledge Hub links
- Fixes a bug with a misnamed DEA Coastlines field

Update CMI links and fix broken Coastlines field

---

products/others/abares_clum_2020/abares_clum_2020.stac-item.json

We can't currently access ABARES data on dev or prod:
I think this is because some of the STAC paths are wrong. I've attempted to fix these below.

Fix paths in ABARES STAC

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/utils_intertidal.py

This adds a new adaptive uncertainty style to match the adaptive elevation style. It scales colours from uncertainty of 10% to 30% of the observed tide range.
Also makes some minor tweaks to the adaptive elevation style.

Add DEA Intertidal adaptive uncertainty layer

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/ows_intertidal_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py

Temporarily remove Extents style from DEA Intertidal OWS layer (data has been removed from the first release of the product)

Remove extents from DEA Intertidal OWS style

---

dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/ows_intertidal_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/ows_category_root_cfg.py
dev/terria/terria-cube-v8.json

Update directory structure, abstract, layer names
Add link to tile grid

Updates to DEA Intertidal OWS and Terria

---

dev/terria/terria-cube-v8.json
prod/services/wms/inventory.json
prod/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/ows_intertidal_cfg.py
prod/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
prod/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/utils_intertidal.py
prod/services/wms/ows_refactored/sea_ocean_coast/ows_category_root_cfg.py

This PR adds DEA Intertidal to prod OWS and the prod section of Terriacube, including a simpler set of three styles (elevation, uncertainty and exposure).
It also updates the prod OWS and prod section of Terriacube to place the older NIDEM and ITEM layers inside "Other".

Prod OWS DEA Intertidal layer

---

prod/terria/dea-maps-v8.json

This PR adds the new DEA Intertidal layers to DEA Maps. 
Test using the "DEA Maps preview" link below: "Explore data > Sea, ocean and coast > DEA Intertidal > DEA Intertidal (Sentinel-2, Landsat)"

Add DEA Intertidal to DEA Maps

---

dev/terria/terria-cube-v8.json
prod/terria/dea-maps-v8.json

DEA Intertidal grid in both dev and prod now point to new geojsons with an additional data access field which points to the tile's data on S3.
On dev it points to the tile's data on dev.
On prod it points to the tile's data on prod.
https://maps.dea.ga.gov.au/#clean&https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/intertidal_add_data_link/prod/terria/dea-maps-v8.json
https://terria-cube.terria.io/#clean&https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/intertidal_add_data_link/dev/terria/terria-cube-v8.json

Intertidal add data link

---

dev/services/alchemist/ga_ls_fc_3/ga_ls8_fc_3.alchemist.yaml

Add LS9 coefficients for processing FC. Given the similarity between LS8 and LS9 at the ARD level and an experiment analysing LS9 pixels under-flying LS8 for the FC, a decision has been made to use LS8 coefficients for LS9.

Add LS9 to FC configuration.

---

dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_cyear_3.yaml

This PR updates the FC Percentile product configuration in the dev in preparation for applying cloud and shadow buffer as well as including the LS9 FC data. The FCP version has been update from 3.0.0 to 3.1.0 since the algorithm hasn't changed.

Update the FC Percentile product configuration in the dev environment.

---

dev/terria/terria-cube-v8.json
prod/terria/dea-maps-v8.json

This PR adds a GeoJSON version of the updated/expanded Collection 3 grid to Terriacube and DEA Maps (see preview links below). It is located in `Other > DEA Shapes`.
To make it clear that the grid is not final and may change, I have included the following caveat:
> This is a provisional layer intended to replace the existing <b>DEA Summary Product Grid (Collection 3)</b> by updating region code IDs to account for new satellite data processed over Australia's external territories.

Add expanded grid to Terria and DEA Maps

---

prod/services/odc-stats/mangroves/ga_ls_mangrove_cover_cyear_3.yaml
prod/services/odc-stats/tc_percentile/ga_ls_tc_pc_cyear_3.yaml

Stats prod run configurations.

Added stats configurations for fractional cover percentile, tasseled cap percentiles and mangroves for prod runs.

---

dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/utils_intertidal.py
dev/terria/terria-cube-v8.json

This is a first pass at adding support for elevation differencing within Terria for DEA Intertidal, making use of new raw data multidate functionality in OWS

Add multidate handling to DEA Intertidal using raw band data

---

.github/workflows/ows_cfg_testing_dev.yaml
.github/workflows/ows_cfg_testing_prod.yaml
dev/services/wms/ows_refactored/baseline_satellite_data/landsat/style_c3_cfg.py

The `geodata_coast_100k layer` ([used to define "land" in our ARD styles](https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py#L181-L184)) has values of 0 (water), 1 (islands) and 2 (land):
But for some reason, the `pq_mask_fmask_land` mask seems to be using [a value of 1 and then inverting it](https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/ows_refactored/baseline_satellite_data/landsat/style_c3_cfg.py#L12-L14)... which seems to be leading to islands being masked but water and land being preserved.
This PR attempts to fix this by [to change this line to](https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/wms/ows_refactored/baseline_satellite_data/la …

Fix island masking bug

---

dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/style_s2_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/landsat/style_c3_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/style_combined_cfg.py
prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/style_s2_cfg.py

Have updated:
- Dev Sentinel-2 layer
- Prod Landsat layer
- Prod Sentinel-2 layer
- Prod combined layer
Dev WMS combined style is old and does not apply masking - we should fix this but not in this PR

Fix masking in remaining ARD styles

---

prod/services/odc-stats/mangroves/ga_ls_mangrove_cover_cyear_3.yaml

The object ownership in the public data account has now changed to "bucket owner enforced" so its no longer needed to define ACL for objects in this bucket.

Delete the ACL as bucket policy is enforced in the prod account.

---

prod/services/odc-stats/wofs_summary/ga_ls_wo_fq_apr_oct_3.yaml
prod/services/odc-stats/wofs_summary/ga_ls_wo_fq_cyear_3.yaml
prod/services/odc-stats/wofs_summary/ga_ls_wo_fq_fyear_3.yaml
prod/services/odc-stats/wofs_summary/ga_ls_wo_fq_myear_3.yaml
prod/services/odc-stats/wofs_summary/ga_ls_wo_fq_nov_mar_3.yaml

No longer required.  s3 ACLs removed from use in destination location

S3 ACL removal

---

products/baseline_satellite_data/c3/ga_s2cm_ard_3.odc-product.yaml

Nothing fancy, just the usual. Data will be coming in on 21/Jan/2025.

Add Sentinel-2C product definition

---

dev/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c3_lc_cyear_cfg.py
prod/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c3_lc_cyear_cfg.py

this PR is to correct the lifeform colour scheme. Now all woody and all herbaceous classes are included in the corresponding lifeform classes.
I also quickly checked the other descriptors, they seem to include all the correct lcasses

Correct colours

---

dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/utils_intertidal.py

This PR tests out adding a custom metadata field to our DEA Intertidal FeatureInfo table, using new `custom_includes` functionality added by @SpacemanPaul last year:
https://github.com/opendatacube/datacube-ows/pull/1039/
https://datacube-ows.readthedocs.io/en/latest/cfg_layers.html#custom-layer-includes-custom-includes
This will hopefully allow us to point to a specific S3 path, generated by combining metadata fields from the dataset being viewed, e.g.:
`f"https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/derivative/ga_s2ls_intertidal_cyear_3/{version}/{region}/{year}--P1Y/tide_graph.png"`
https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/derivative/ga_s2ls_intertidal_cyear_3/1-0-0/x137/y175/2022--P1Y/tide_graph.png

Trial adding custom metadata to DEA Intertidal FeatureInfo

---

dev/services/wms/inventory.json
dev/services/wms/ows_refactored/sea_ocean_coast/tidal_composites_c3/ows_tidal_composites_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/tidal_composites_c3/style_tidal_composites_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/tidal_composites_c3/utils_tidal_composites.py

This PR adds low and high tide threshold layers to OWS so we can hopefully use them in a FeatureInfo popup.
It also adds two experimental log-scaled true colour styles, intended to test whether we can use a single style that works well in dark and bright coastal environments (e.g. avoiding bright beaches from being washed out).

Experimental tidal composite OWS updates

---

dev/services/wms/ows_refactored/sea_ocean_coast/tidal_composites_c3/style_tidal_composites_cfg.py
dev/services/wms/ows_refactored/sea_ocean_coast/tidal_composites_c3/utils_tidal_composites.py
dev/terria/terria-cube-v8.json

Set DEA Tidal Composites to default to 2022 data
Use a softer transform (log instead of log10) in experimental layer to improve visualisation

Test setting default time on tidal composites, update styling

---

products/baseline_satellite_data/README.md
products/baseline_satellite_data/s1_gamma0/ga_s1_rtc_backscatter_experimental.odc-product.yaml

Add a product definition for Radiometric Terrain Corrected (RTC) Backscatter for Sentinel-1 generated from the COMPASS-ISCE3 pipeline. This is an experimental product that will be added and indexed into the dev ODC for now. This will allow our end users to try out the product before proceeding to continental processing over Australia and Antarctica.
Please delete options that are not relevant.
After starting a container for `datacube-index` and connecting it to a Postgis database, I ran the following commands:
```
datacube product add https://raw.githubusercontent.com/caitlinadams/dea-config/refs/heads/master/products/baseline_satellite_data/s1_gamma0/ga_s1_rtc_backscatter_experimental.odc-product.yaml
export AWS_DEFAULT_REGION=ap-southeast-2
s3-to-dc --stac --no-sign-request …
```

Add initial experimental product definition for GA S1 RTC Backscatter

---

product_metadata/eo3_s1_ard.odc-type.yaml
products/baseline_satellite_data/README.md
products/baseline_satellite_data/s1_gamma0/ga_s1_iw_hh_c0.odc-product.yaml
products/baseline_satellite_data/s1_gamma0/ga_s1_iw_hh_hv_c0.odc-product.yaml
products/baseline_satellite_data/s1_gamma0/ga_s1_iw_vv_c0.odc-product.yaml
products/baseline_satellite_data/s1_gamma0/ga_s1_iw_vv_vh_c0.odc-product.yaml

Add product definitions for Radiometric Terrain Corrected (RTC) Backscatter for Sentinel-1 generated using the OPERA pipeline. This is an experimental product definition that will be used to allow users to supply feedback. For now, we have not included static layers in the definition. This will be done when we move from c0 (experimental) to c1 (first collection release)
I have tested this product definition locally in a `datacube-index` container. I have tested similar product definitions in the dev-datacube. I used the following commands:
```
datacube system init
datacube metadata add https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/refs/heads/ga_s1_intermediate_definition/product_metadata/eo3_s1_ard.odc-type.yaml
datacube product add …
```

Add intermediate product definitions for Sentinel-1 gamma0 backscatter

---

product_metadata/eo3_s1_ard.odc-type.yaml

Converting types of STAC boolean flags from incorrect `integer` type to `string` type. Integer fails when trying to run summaries in Explorer, and newly added boolean type isn't working for dev datacube.

convert metadata types from integer to string
