dev/products/geomedian-au/geomedian_nbart_annual.yaml, prod/products/geomedian-au/geomedian_nbart_annual.yaml
the geomedian product definition will be no longer available on GeoscienceAustralia/digitalearthau repo
=> add product definition for geomedian

dev/services/wms/ows/wms_cfg.py, dev/services/wms/wofs/wms_cfg.py, prod/services/wms/geomedian-au/wms_cfg.py
Update the prod services for geomedian-au to ``` DEA geomedian terrain corrected surface reflectance```
Add wofls and wofs_summary to wofs layer
=> Merge config

dev/dea-terria.json
For rapid prototyping with Data61
=> Add draft DEA config for Terria-Cube

dev/products/ls8-bare-earth/landsat8_barest_earth_mosaic.yaml
- The tile value is changed to 25km
=> Add product definition for ls8 bare earth

dev/terria/dea.json
Add Barest Earth Dev service and Production K8s
=> Add Barest Earth Dev service and Production K8s

dev/terria/dea.json
Order WOfS Summary layers according to product owner
=> Order WOfS layers according to product owner

dev/services/wms/ows/wms_cfg.py
- Add NDSI
- Add Soil composition index
- Add  hematite-goethite index
- Add iron 2+ and 3+
- Add Clay/hydroxyl-bearing minerals
=> update indices for bare earth

dev/terria/dea.json
As we have consolidated a number of services, we are removing those endpoints from this catalog.
=> Remove excess endpoints

dev/terria/dea.json
=> URL to Url

dev/services/wms/ows/wms_cfg.py
Add nodata comparisons to extent mask functions. Specify ticks for weather product
=> MSTP and Weathering config changes

dev/terria/dea.json
Add multi_scale_topographic_position and weathering_intensity
=> Add additional Geophysical layers

dev/terria/dea.json
=> Add GSKY WOFLs legend

dev/services/wms/ows/wms_cfg.py, prod/services/index/ows/wms_cfg.py, prod/services/wms/ows/wms_cfg.py
For Weathering Intensity and MSTP
=> Remove bad ecat links

dev/terria/dea.json
Remove old ECS, remove GSKY with legends, remove Geoglamm layers
=> Remove redundant catalogue entries

prod/services/wms/ows/wms_cfg.py
change metadata to be 90-day rolling archive, 
remove zoom level comment as we now support overviews.
=> Fix NRT Metatdata

dev/products/fc/fc_percentile_albers_annual.yaml, dev/services/index/ows/wms_cfg.py
- update fcp definition
- add fcp styles
=> Fractional Cover Percentiles

dev/terria/dea.json
Add FCP to Terria default styles
=> Add FCP to Terria catalogue

dev/services/wms/ows/wms_cfg.py
making the product owner happy
=> FCP metadata fixes

dev/services/wms/ows/wms_cfg.py
Add Sentinel 2 grayscale layers
=> Add Sentinel 2 grayscale layers

dev/services/wms/ows/wms_cfg.py
add '(SWIR)' to SWIR style names
=> add '(SWIR)' to SWIR style names

prod/services/wms/ows/wms_cfg.py
add sentinel 2 grayscale styles back to prod
=> add sentinel 2 grayscale styles back to prod

dev/services/wms/ows/wms_cfg.py, prod/services/wms/ows/wms_cfg.py
Update Sentinel 2 NDWI label to NIR from SWIR
=> Update Sentinel 2 NDWI label to NIR from SWIR

dev/terria/dea.json
Add NIDEM, set default opacity, reorder GSKY groups
=> Add NIDEM, set default opacity, reorder GSKY groups

dev/products/wofs/wofs_annual_summary.yaml
WOfS Annual Summary product definition
=> Wofs annual

dev/services/wms/ows/wms_cfg.py, prod/services/wms/ows/wms_cfg.py
Update production ndvi and ndwi styles for new legend configuration. Add single band styles to geomedian products
=> Production NDVI, NDWI color ramp changes & Geomedian single band

dev/terria/dea.json
Add bad wofls, and htltc to dev catalogue
=> Add bad wofls, and htltc to dev catalogue

dev/services/wms/ows/wms_cfg.py
Add updated Layer descriptions for WOfS summaries in Dev
=> Add updated Layer descriptions for WOfS summaries in Dev

dev/services/wms/ows/wms_cfg.py
Add noncontiguous to invalid wofs colour ramp
=> Add noncontiguous to invalid wofs colour ramp

dev/terria/dea.json
=> Add ITEM layers to Terria

dev/services/wms/ows/wms_cfg.py
GetFeatureInfo for NEII stream gauge mashup with GSKY data
=> Include UTC dates for GSKY lookup

dev/terria/dea.json
Change links to use the pretty url
=> Change shape links to point to data.dea.ga.gov.au

dev/terria/dea.json
=> Fix WOfS name

dev/services/wms/ows/wms_cfg.py
Increase the amount of yellow in WOfS clear observations to make higher values easier to distinguish
=> Reduce the green in clear observations

dev/terria/dea.json
In the last PR, I missed the prod version, and didn't update the order of the units
=> Actually fix columns

dev/terria/dea.json
Add Sentinel 2 demo link
Add new GSKY services
=> Update GSKY groups

dev/services/wms/ows/wms_cfg.py
Add additional style for WOfS Daily observations.
=> Add WOfL wet style

dev/services/wms/ows/wms_cfg.py
change 'water' style to observations,
change wet style to Wet Only
=> Wofs daily styles

.travis.yml
Move git hash to metadata field in docker image tags
=> Update image tags

.travis.yml
Reverts GeoscienceAustralia/dea-config#220
=> Revert "Update image tags"

dev/services/wms/ows/wms_cfg.py
Adding wofs april to october styles
=> add wofs april to october

dev/services/wms/ows/wms_cfg.py
Add the November - March season config for seasonal WOfS
=> Add WOfS Seasonal November to March Config

dev/services/wms/ows/wms_cfg.py
also add status page to geomedian,  HLTC an ITEM
=> fix geomedian metadata, so it shows up in nationalmap

dev/products/hap_product.yaml, dev/services/wms/ows/wms_cfg.py
Add product definition and WMS config for Historical Airborne Photography (HAP) mosaic.
=> Proof of concept WMS for HAP mosaic

dev/services/wms/ows/wms_cfg.py, dev/terria/dea.json
Disabling the dam map layers from dev and prod until it is ready to launch
=> Disable dam map

dev/services/wms/ows/wms_cfg.py
After some interest in the NDCI layers from stakeholders we're testing an adjustment to the thresholding, This change will require approval from Med before it is pushed to production.
=> drop NDCI threshold to 0.1 as per Steve Sagar's request

dev/services/wms/ows/wms_cfg.py
`prefix=` is only for directory browsing
=> Fix broken S3 links for WOfS Product PDFs

dev/services/wms/nrt/wms_cfg.py
Includes multi-product combined sentinel2 layer.
=> Add merged Sentinel2 multi-product layer.

dev/services/wms/ows/wms_cfg.py, dev/terria/dea.json
=> Re-enable nsw dam map

dev/terria/dea.json
Fix incorrect dave service endpoint
=> Fix incorrect dave service endpoint

dev/services/wms/thredds/wms_cfg.py
based on https://www.earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-modis/normalized-burn-index-dNBR/
=> add NBR to s2 definitive

dev/services/wms/thredds/wms_cfg.py
it is sad, this will make it less sad
=> disable nbr legend

dev/services/wms/ows/wms_cfg.py
Put correct scale and metadata in legends and service description for ASTER maps.
=> Fix legends and metadata for ASTER maps

dev/products/fc/ls5_fc_albers.yaml, dev/products/fc/ls7_fc_albers.yaml, dev/services/wms/ows/wms_cfg.py
-  int16 as dtypes
- Add LS7 definition
=> Fractional Cover product updates

dev/products/cambodia/wofs_product.yaml
~30 year water classifier summary for Cambodia
=> add Cambodia WOfS product description 

dev/services/wms/ows/wms_cfg.py
- Add pq_data_fuser to fc products.
- Update FC product metadata
=> Fractional cover updates

dev/terria/dea.json
Add FC Daily observations to Terria Dev
=> Add FC Daily observations to Terria Dev

dev/services/wms/ows/wms_cfg.py
Add FCP Legend to Daily FC and set the scale range to 0-100
=> Add FCP Legend to Daily FC and set the scale range to 0-100

dev/terria/dea.json
Remove old GSKY and THREDDSKY groups
Add Dev Threddsky to dev group
Add featureTimesProperty for threddsky
=> Remove old GSKY and THREDDSKY groups

dev/services/wms/ows/wms_cfg.py
- Add pq_product array to fc combined product
- Update zoom levels for FC daily observation products
=> Fractional Cover Daily Updates

dev/services/wms/ows/wms_cfg.py, dev/terria/dea.json
- Add individual WPS entries for WOfS pixel drill and FC polygon drill to Terria catalog.
- Update FC daily observation WMS descriptions
=> FC catalog and description updates

dev/terria/dea.json
=> Add Hotspots Layers

dev/terria/dea.json
Added Wetlands Insight template info to catalogue
=> Add Wetlands Insight Tool to dea.json catalogue

dev/services/wms/ows/wms_cfg.py
Just for the rainbow style, not for blues.
Annual uses a different ramp, so we can't use the same image
=> Change WOfS all-time frequency layers to use legend url

dev/terria/dea.json
Update wetlands insight tool name
from: 
"name": "DEA Ramsar Wetlands draft polygons",
to:
"name": "DEA Wetlands Insight Tool v1.0",
=> Update wetlands insight tool name

dev/terria/dea.json
=> Need to update geojson file!

dev/terria/dea.json
=> change geojson shapefile

dev/services/wms/ows/wms_cfg.py
Add barest earth 30y config in ows/wms_cfg
=> Add barest earth 30y config in ows/wms_cfg

dev/terria/dea.json
Hi,
This pull request is to add the  MODIS Marine Heat Waves Tools into DEA Shapes under Terria Map. 
Many thanks
Zhi
=> Add MODIS Marine Heat Waves Tools into DEA Shapes

dev/terria/dea.json
Thanks Harshu for pointing out the mistake. I have updated the dea.json. 
Regards
Zhi
=> update dea.json for the Marine Heat Waves Tool

dev/services/wms/thredds/wms_cfg.py
potential error when updating multi product ranges
=> fix wms name for threddsky

dev/terria/dea.json
=> Add Fiji Geomedian

dev/terria/dea.json
Adding livestock recovery to WIT tool applications. I think the shapefile shouldn't be too big, but if this doesn't load quick enough I have a rasterized version in the works.
=> Adding livestock recovery agency dea-shapes

dev_3-0-0/products/ga-landsat-ard-3-0-0/ga_landsat5_ard_v3-0-0.yaml, dev_3-0-0/products/ga-landsat-ard-3-0-0/ga_landsat7_ard_v3-0-0.yaml, dev_3-0-0/products/ga-landsat-ard-3-0-0/ga_landsat8_ard_v3-0-0.yaml
Add landsat5, landsat7, and landsat8 product definitions
=> Add sample ard new collection upgrade product definitions

dev/services/wms/ows/wms_cfg.py
Added correct journal article references to MNDWI and NDWI, and updated NDWI colour scheme to evaluate prior to updating GSKY as discussed with Dave
=> Update water index metadata and test updated NDWI colour scheme

dev/terria/dea.json
Remove devinitive typo from terria catalog.
=> Remove devinitive typo

dev/services/wms/ows/wms_cfg.py
This change makes the two HLTC layers use the same bands/indices as the geomedians, and adds in legends for MNDWI on all layers
=> Add legends to MNDWI and make HLTC consistent with other layers

dev/services/wms/ows/wms_cfg.py
By default the scale is set to 0-1 , specifying 'scale-by' should fix the actual scale
=> Fix legend scaling for `ndwi`

dev/terria/dea.json
Seperate True Colour and False Colour layers for Blended Service
=> Update Blended Service on Terria  for different layers

dev/services/wms/ows/wms_cfg.py, dev/terria/dea.json
Following are the changes implemented in the PR:
- Add ecat dataset record link to all the individual `ASTER` products
- Minor documentation updates
- Sync `ASTER` layer names between `wms_cfg.py` file and terria catalog `dea.json` file.
=> Add ecat dataset record to ASTER layer

dev/terria/dea.json
First attempt at updating this json, so please check I have the template correct
=> Adding 'irrigation insight tool' to json

dev/products/wofs/wofs_albers.yaml
- add grid spec
- fix masking for `nodata` bit -- allow using False and not just True
=> Fix wofs albers product spec

dev/terria/dea.json
Add a new csv listing to view the S3 accessed `product of interest` and `area of interest for month basis
=> csv listing to access/view s3 data download from dea public bucket

dev/terria/dea.json
QLD wits on Terria for stakeholders
=> include version 1 of the QLD WITs on Terria

dev/services/wms/ows/wms_cfg.py, dev/terria/dea.json
- Rename Barest Earth product names to Landsat-8 Barest Earth and Landsat 30+ Barest Earth
- Update product description for Landsat 30+ Barest Earth product
- Update new style layers color ramp values for Landsat 30+ Barest Earth product
=> More updates based on review comments

dev/terria/dea.json, prod/services/wms/ows/wms_cfg.py
- Add `WAMM` to prod `wms` config
- Update `Terria` catalogue to list WAMM in DEA Production group
=> Add WAMM to prod wms config and update Terria catalogue

dev/terria/dea-maps.json
Add leafletUpdateInterval to layer config to prevent SPDY errors in 2D mode.
=> Add leafletUpdateInterval to layer config

dev/terria/dea-maps.json
Update the `leafletUpdateInterval` from 500ms to 750ms to try and make it more tolerant for SPDY.
=> Update delay from 500 to 750ms

dev/services/wms/ows/wms_cfg.py
- Update abstract description for Barest Earth 30+ as per Dale's suggestion
- Test color ramp for Barest Earth 30+ Ferric Iron and Normalised Difference Soil Index styles
=> Test color ramp on barest earth 30+

dev/services/wms/ows/wms_cfg.py
- Minor changes to color codes for Barest Earth 30+ styles
=> Patch barest earth 30y color ramp

dev/services/wms/ows/wms_cfg.py, dev/terria/dea.json
Following are the changes implemented in this PR:
- Release tmad product to dev terria
- Add color ramps to tmad
=> Update tmad styles and release tmad to dev

dev/terria/dea-maps.json
Add Hotspots layers for data61 testing
=> Add Hotspots

dev/services/wms/ows/wms_cfg.py
- Test layer improvements to tmad
=> More updates to tmad layer

dev/terria/dea.json
=> Add WAMM back to terria-cube

dev/services/wms/ows/wms_cfg.py
- Apply logarithmic transform for `tmad` data values without use of `math.log` function
- Comment min zoom factor for tmad products
=> Patch tmad lambda function

dev/services/wms/ows/wms_cfg.py
- Refine legend text
- Enable min zoom factor
=> Update tmad styles

dev/terria/dea.json
- Release barest earth 30 yr to prod, similar to that of dev terria
=> Release barest earth 30yr to prod

dev/services/wms/ows/wms_cfg.py
Swap ramp color codes to indicate low tmad values as green and high tmad values as red
=> Swap ramp color codes for tmad

dev/terria/dea-maps.json
- Change GSKY blended service layers to single style layer
- Add data available for dates to daily landsat from GSKY
- Remove legends from hotspots
=> Update GSKY and Hotspots layers

dev/services/wms/ows/wms_cfg.py
We are temporarily bringing this back up for a demo
=> Adding of approved text to WAMM wms.

dev/services/wms/ows/wms_cfg.py
=> Enable WAMM on Dev

dev/terria/dea.json
=> removal of dea waterbodies from terria

prod/services/wms/ows/ows_cfg.py
=> Disable sentinel 2 wofs

prod/services/wms/ows/ows_cfg.py
Products not released to prod yet
=> Disable HAP and TMADs

dev/terria/dea-maps.json, dev/terria/dea.json
=> Add hotspots cors

dev/terria/dea.json
Deploy layer for terria via ows-config refactor server.
=> #470 Add Terria config

dev/services/wms/ows/ows_cfg.py
Add 8 Data products derived from ALOS-PALSAR
- Displacement x2 ( EW and UD)
- Velocity x2 (EW and UD)
- Standard-deviations for the above x4
=> #470 Deploy all alos derived data

dev/terria/dea.json
Add all 8 ALOS Layers for terria in dev
=> #470 Add ALOS terria config

dev/services/wms/ows/ows_cfg.py
Add all 24 layers for NSW InSAR
=> #470 Add all NSW SAR products

dev/terria/dea-maps.json
Remove CQL filter so that hotspots work
=> Remove CQL filter

dev/services/wms/ows/ows_cfg.py
Patch scaling for tide products in dev.
=> #483 Hotfix for new scaling

prod/services/wms/ows/ows_cfg.py
as per #483 scale HLTC values correctly, this time in the production environment
=> fix hltc styles

prod/services/wms/ows/ows_cfg.py
Add dynamic flag to nrt products
=> add dynamic flag to nrt in production ows

dev/services/wms/ows/ows_cfg.py
Add layer descriptions according to science team requirements. To be maintained in the future via direct PR's from science team.
=> Terria nsw sar

dev/terria/dea.json
Added Folder level metadata for display in Terria. Ideally this should be a Terria.js enhancement to fetch folder level metadata published by WMS and show it in the folder.
=> #470 Add Terria folder level description

dev/terria/dea-maps.json
Could someone please approve and merge this pull request on Monday after Claire K says GO.
Thanks!
=> Add DEA waterbodies to dea maps

dev/terria/dea.json
Added the updated version for comparison with V1
=> adding WIT_version2 for work with CEWO

dev/terria/dea.json
Add Production combined S2 NRT layer to Terria catalogue.
=> Add Production combined S2 NRT layer

dev/terria/dea.json
editing terria json to load WIT v3 for QA/QC
=> add most recent WIT version for QA/QC

prod/services/wms/ows/ows_cfg.py
as per #527 
dev looks good, so moving to production now
=> Configure prod sentinel 2 definitive to be dynamic

dev/terria/dea-maps.json
Fix embarassing catalog typos - why do they let me near a keyboard?
=> Fix HLTC catalog typos

dev/terria/dea.json
Add GSKY collection 3 beta endpoints for testing of removed zoom level restrictions
=> Add GSKY Beta 16-day composites for testing

dev/services/wms/ows/ows_cfg.py, dev/terria/dea.json
- enable delta for sentinel layers
- correct color ramp  based on gsky nbr
=> Nbr update

dev/services/wms/ows/ows_cfg.py
- all layers reviewed, 
- correction applied to ows config
- this fix is for dev
=> WCS resolution review

prod/services/wms/ows/ows_cfg.py
- clean up trailing spaces
- consistent indentation
- add `renders` for wcs2.0 changes
- fix `weathering_intensity` and `multi`
=> 1.8.x prod release

dev/terria/dea.json
=> Add GSKY Beta WPS endpoints

dev/services/wms/ows/ows_cfg.py
Dev legend changes for  OWS autolegend generation changes.
=> Legend refactor

dev/services/wms/ows/ows_cfg.py
copy.copy is overriding the other legend range
=> fix copy.copy issue

dev/services/wms/ows/ows_cfg.py
Missed the dev stack in my previous change:
Add band names to band alias list for Landsat and Sentinel 2 bands
=> Add band name to band alias dev

prod/services/wms/ows/ows_cfg.py
Compatible legend for latest code
=> Chage legend to latest format

dev/services/wms/ows/ows_cfg.py
- fix insar legend where `tick_every` needs to be override to fit within the range
=> Add missing ticks_every

dev/services/wms/ows/ows_cfg.py
- change `dataset` to `product`
- change `datasets` to `products`
- adjust `native_resolution` as per warning message
=> Adjust config as per ows warning messages

dev/services/wms/ows/ows_cfg.py
- change `end` from `20` to `30` as per name suggests
- add `_ticks_20` 
- make `fc` use reusable blocks
=> Fix legend for ows dev

prod/services/wms/ows/ows_cfg.py
- fix typo for thirty
- add ticks_20 for 20 intervals
- add `native_resolution`
- change `dataset` to `product` and `datasets` to `products`
=> Fix ows config for newcode

dev/services/wms/ows/ows_cfg.py, prod/services/wms/ows/ows_cfg.py
- cleanup old legend config
- cleanup crs
- fix typo
- fix outstanding broken legend
=> Ows 181 config prep

dev/services/wms/ows/ows_cfg.py
latest ows is broken when manual merge is set to true
=> Manual merge is broken

dev/services/wms/ows/ows_cfg.py
Reverts GeoscienceAustralia/dea-config#570
datacube-ows will fix manual merge
=> Revert "Manual merge is broken"

dev/terria/dea-maps.json
Temporary test of config prior to DEA Coastlines release. This will be taken down once we verify everything is working correctly.
=> Test of DEA Coastlines config in DEA Maps

dev/terria/dea-maps.json
Revert temporary inclusion of DEA Coastlines in DEA Maps config
=> Restore original DEA Maps config

prod/services/wms/ows/ows_cfg.py
=> #579 Deploy NSW InSAR to prod

.github/workflows/main.yml
Migrate Pylint step from Travis to GHA. Closes #580
=> #580 Run pylint in Github actions

.github/workflows/main.yml, dev/services/wms/ows/ows_cfg.py, dev/terria/dea.json
```
Run npm install jsonlint -g
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! …
```
=> Fix linting and format ows_cfg

dev/terria/dea-maps.json
Add ows prod based Terria Catalog entry for Camden InSAR
=> #579 Deploy NSW InSAR to Dea-Maps

dev/terria/dea-maps.json
The services return feature information with the following properties:
```
{
"properties": {
"data": [
{
"time": "2010-10-22 01:01:01 UTC",
"bands": {
"ew": -41.41450119018555,
"ud": -57.37554931640625,
"ewstd": 8.687277793884277,
"upstd": 8.62914752960205
}
}
],
"lon": 150.93103408813067,
"lat": -34.1929196405549,
"data_available_for_dates": [
"2008-02-11",
"2008-02-23",
"2008-03-06",
"2008-03-18",
"2008-03-30",
"2008-04-11",
"2008-04-23",
"2008-05-05",
"2008-05-17",
"2008-05-29",
"2008-06-10",
"2008-06-22",
"2008-07-04",
"2008-07-16",
"2008-07-28",
"2008-08-09",
"2008-08-21",
"2008-09-02",
"2008-09-14",
"2008-09-26",
"2008-10-08",
"2008-10-20",
"2008-11-01",
"2008-11-13",
"2008-11-25",
"2008-12-07",
"2008-12-19",
"2008-12-31",
"2009-01-12",
"2009-01-24",
"2009-02-05",
"2009-02-17", …
```
=> Add Terria feature info templates to NSW InSAR

dev/terria/dea.json
Backport Stephen Davies chanes to Terria-cube
=> Backport featureInfo template for insar layers

workspaces/prod-products.csv
that dea-datakube repository has been unmaintained for 2 years,
although this is being updated now, it is still worth to update it in the mean time
=> Update csv record

dev/services/wms/ows/ows_cfg.py
"Sensitive" versions of TMAD styles as requested by Dale.
Uses config inheritance.
=> Added "sensitive" versions of tmad styles.

prod/services/wms/ows/ows_cfg.py
fix for https://github.com/GeoscienceAustralia/dea-config/issues/597
=> correct legend for fcp annual

dev/services/wms/ows/ows_cfg.py
- change `pass_product_cfg` to `mapped_bands` to align with recent ows change
- change `"manual_merge":` to  `False` for non-solar corrected layers
- add s2_nbar bands
- add s2_nbar layers
=> Add s2 nbar

dev/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml
* Add the WO config
* Add the FC config
=> Adding in WO and FC dev config files

dev/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml
=> Update alchemist configs for dev

.github/workflows/docker-image.yml, .mergify.yml
Direct copy-paste from OWS CI closes #534
=> Follow git based tag extraction pattern

prod/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, prod/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml, prod/services/alchemist/readme.md
- Getting ready for production
=> Add production Alchemist configs

.github/ISSUE_TEMPLATE/ows-layer-request.md
This templates provides the minimal information to get started on a new OWS layer, iteratively the details can be refined,
=> ows layer request template

dev/services/wms/ows/ows_cfg.py
A more sensitive version of the `tmad_rgb_sensitive` style.
=> A more sensitive version of tmad_sensitive.

prod/services/wms/ows/ows_cfg.py
```
[2020-11-24 02:20:55,266] datacube_ows.ows_configuration [None] [WARNING] Manual merge is only recommended where solar correction is required.
[2020-11-24 02:20:55,268] datacube_ows.ows_configuration [None] [WARNING] Manual merge is only recommended where solar correction is required.
WARNING: pass_product_cfg in function wrapper definitions has been renamed 'mapped_bands'.  Please update your config accordinglyWARNING: pass_product_cfg in function wrapper definitions has been renamed 'mapped_bands'.  Please update your config accordingly
```
=> update ows cfg for the latest version warnings

dev/services/wms/ows/ows_cfg.py
- move tasselled cap legend text out of bracket.
=> Move legend unit out of bracket

dev/services/wms/ows/ows_cfg.py
- waterbody has been approved to be deleted from dev
- retiring it from ows
=> Retire water bodies from ows as product is getting deleted

prod/services/wms/ows/ows_cfg.py
- This waterbodies config in ows has been a placeholder ,commented out in the file
- removing it completely as it is not supported
=> Remove waterbodies from prod ows config

prod/services/wms/ows/ows_cfg.py
Add standard TMAD styles as a first cut in prod now that products exist in the datacube
=> #569 enable standard TMAD styles

prod/services/wms/ows/ows_cfg.py
Add 2 new TMAD styles
Signed-off-by: Tisham Dhar <tisham.dhar@ga.gov.au>
=> #569 add extra TMAD styles

dev/terria/dea.json
=> Prettifer dea json

.gitignore, dev/services/wms/ows_refactored/README.md, dev/services/wms/ows_refactored/aster/ows_aster_cfg.py, dev/services/wms/ows_refactored/c3/ows_c3_cfg.py, dev/services/wms/ows_refactored/fc/ows_fc_albers_cfg.py, dev/services/wms/ows_refactored/fc/ows_fc_percentiles_cfg.py, dev/services/wms/ows_refactored/fc/style_fc_cfg.py, dev/services/wms/ows_refactored/insar/ows_insar_cfg.py, dev/services/wms/ows_refactored/ows_legend_cfg.py, dev/services/wms/ows_refactored/ows_reslim_cfg.py, dev/services/wms/ows_refactored/ows_root_cfg.py, dev/services/wms/ows_refactored/sentinel2/ows_ard_cfg.py, dev/services/wms/ows_refactored/sentinel2/ows_nrt_cfg.py, dev/services/wms/ows_refactored/sentinel2/style_s2_cfg.py, dev/services/wms/ows_refactored/surface_reflectance/band_ls_cfg.py, dev/services/wms/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, dev/services/wms/ows_refactored/surface_reflectance/ows_nd_cfg.py, dev/services/wms/ows_refactored/surface_reflectance/style_ls_cfg.py, dev/services/wms/ows_refactored/tide/ows_intertidal_cfg.py, dev/services/wms/ows_refactored/tide/ows_tide_cfg.py, dev/services/wms/ows_refactored/tmad/ows_tmad_cfg.py, dev/services/wms/ows_refactored/wofs/ows_nrt_wo_cfg.py, dev/services/wms/ows_refactored/wofs/ows_wofs_cfg.py
spitting ows_cfg into files less than 1k line
=> split mega ows_cfg file to manageable size

.github/workflows/main.yml, .github/workflows/ows_cfg.yaml, dev/services/wms/ows_refactored/c3/ows_c3_cfg.py, docker-compose.ows.yaml
- testing for multi-file ows_cfgs
=> setup ows docker to test ows refactored

dev/services/wms/README.md, dev/services/wms/ows_refactored/README.md
=> add more readme

.github/workflows/docker-image.yml
- only build new docker image when there is change to ows.
@alexgleith @omad unless you guys depend on docker images for other stuff?
=> only build when changes to ows

dev/terria/dea.json
Closes #649 park band-math samples for user-testing.
=> #649 Add GSKY band-math sample group

dev/terria/dea.json
=> Swap to alpha

dev/terria/dea.json
taken from here: https://www.linkedin.com/pulse/ndvi-ndbi-ndwi-calculation-using-landsat-7-8-tek-bahadur-kshetri
=> Add more complicated Band Math Examples

dev/terria/README.md
great information needing to be written
=> add readme to terria folder

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/tmad/ows_tmad_cfg.py
```
The config issue is that the three style_tmad_*dev  styles should be deleted (keeping the style_tmad_*dev_std  styles).
```
=> remove log_mad*

dev/terria/dea.json
Add Delta config for GSKY Collection 3 services
=> Add Delta config for GSKY Collection 3 services

dev/services/wms/ows/ows_cfg.py, dev/services/wms/ows_refactored/ows_root_cfg.py
Remove "munged" from name of HAP
=> Remove "munged" from name of HAP

dev/services/alchemist/s2_nrt_wo/s2_nrt_wo.alchemist.yaml
Added a configuration file for S2 NRT WO. Seems to work locally!
=> Added S2 NRT WO config

dev/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml, dev/services/alchemist/s2_nrt_wo/s2_nrt_wo.alchemist.yaml, prod/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, prod/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml
Doesn't break anything, and will be used when we update Alchemist.
=> Add transform URL configuration for Alchemist

dev/services/wms/ows_refactored/wofs/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/wofs/ows_wofs_cfg.py, dev/services/wms/ows_refactored/wofs/ows_wofs_seasonal_cfg.py, dev/services/wms/ows_refactored/wofs/ows_wofs_summary_cfg.py
- add clarity to wofs grouped layers
- increase wofs new style legend size
=> add more clarity to wofs groups

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
- fix panchromic style title
- fix c3 false color range
=> fix c3 landsat styles

dev/services/wms/ows_refactored/wofs/ows_wofs_cfg.py
remove sea, invalid transparent, orange solar/steep
=> Erin telferv3

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
Change false colour style to be copy of Geomedian ( Green, SWIR, NIR
=> Update False Colour Style

dev/services/wps/ows/datacube-wps-config.yaml
Adds the datacube-wps-config.yaml config to dev services
=> Adds WPS datacube config to dev services

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
Change "Simple RGB" style to "True Colour" as per advice in #681
=> Change "Simple RGB" to "True Colour"

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
Update indice style labels in line with #681
=> Update indice style labels

dev/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py, dev/services/wms/ows_refactored/wofs/ows_wofs_cfg.py, dev/services/wps/ows/datacube-wps-config.yaml
- revert wofs wet only style, 
- align c2 style wet only
=> remove borken config for wet only

dev/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml
Update dev alchemist templates
=> Add dask and aws_unsigned

dev/services/wps/ows/pywps.cfg
updates WPS config to use terraform managed  S3 bucket
=> updates WPS config to use terraform managed  S3 bucket

dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml, prod/services/alchemist/ga_ls_fc_3/ga_ls_fc_3.alchemist.yaml, prod/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml
* Use better dask chunks
* Add new config to flag no-sign AWS requests
* Fix formatting
=> Update Alchemist config for Sandbox

dev/services/wms/ows_refactored/wofs/ows_wofs_cfg.py
I have updated the colour code for a few of the layers within the water observation section.
I have also rearranged the layer order.
=> updated order and colour style

dev/services/wms/ows_refactored/wofs/ows_wofs_cfg.py
changed the hex code for the cloud and terrain shaddow
=> change colour of clouds and terrain shadow

dev/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py
updated c3 colour style and layer order to match C2 WO
=> update c3 WO colour style

.github/PULL_REQUEST_TEMPLATE/ows_cfg_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/product_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/terria_pull_request_template.md
enhancement to the repo as requested in https://github.com/GeoscienceAustralia/dea-config/issues/691
=> Pr template

dev/services/wms/ows_refactored/fc/ows_fc_albers_cfg.py, dev/services/wms/ows_refactored/fc/ows_fc_percentiles_cfg.py, dev/services/wms/ows_refactored/fc/style_fc_cfg.py, dev/services/wms/ows_refactored/intertidal/ows_national_cfg.py, prod/services/wms/ows_refactored/fc/ows_fc_albers_cfg.py, prod/services/wms/ows_refactored/fc/ows_fc_percentiles_cfg.py, prod/services/wms/ows_refactored/fc/style_fc_cfg.py, prod/services/wms/ows_refactored/intertidal/ows_national_cfg.py
- refactor `fc` layers
- update layers from deprecated config to the latest compatible format
Fixes # (issue)
Please delete options that are not relevant.
- [ x ] Updating an existing layer
- [ x ] Updating an existing style for layer(/s)
- [ x ] Refactor ows_cfg
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [ x ] Test locally
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have checked my code and corrected any misspellings
=> fix ows deprecated config

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
=> set fmask for c3 ls

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
=> add invert true

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py
Move NBR to be adjacent to other indices
=> Move NBR to be adjacent to other indices

dev/services/alchemist/s2_nrt_wo/s2_nrt_wo.alchemist.yaml
=> Added aws-unsigned: false to S2 NRT WO

dev/terria/dea.json
nrt wofs was removed from ows, clean up terria catalog
=> remove nrt wofs

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/c3/style_c3_cfg.py, prod/services/wms/ows_refactored/c3/ows_c3_cfg.py
Feel free to suggest alternate colours
(previous PR updated prod instead of dev)
=> Quick fmask style

dev/terria/.prettierrc, dev/terria/README.md, dev/terria/dea-maps.json, dev/terria/dea.json
- include `.prettierrc` for consistency
- add prettify instruction to doc
- apply 4 space rule for both json files.
=> add prettify instruction

dev/services/wms/ows_refactored/c3/ows_c3_cfg.py, dev/terria/dea.json
As per discussion with DEA, update ARD layer abstracts to reflect CMI "What this product offers" sections as well as link back to CMI.
=> C3 ARD abstract as per CMI

dev/services/wms/ows_refactored/fc/ows_c3_fc_cfg.py
Update C3 FC Abstract as per CMI
=> C3 FC Abstract as per CMI

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/fc/ows_c3_fc_cfg.py, prod/services/wms/inventory.json, prod/services/wms/ows_refactored/c3/ows_c3_cfg.py, prod/services/wms/ows_refactored/c3/style_c3_cfg.py, prod/services/wms/ows_refactored/fc/ows_c3_fc_cfg.py, prod/services/wms/ows_refactored/ows_root_cfg.py, prod/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py, prod/services/wms/ows_refactored/wofs/ows_wofs_cfg.py
- remove `fc_simple` from c3 fc layer
- mirror all c3 layers to prod
- update inventory.json to reflect the change
=> c3 review action

dev/services/wms/ows_refactored/fc/ows_c3_fc_cfg.py, dev/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py, prod/services/wms/ows_refactored/fc/ows_c3_fc_cfg.py, prod/services/wms/ows_refactored/wofs/ows_c3_wo_cfg.py
- fix pq mask for c3 fc
- remove repeating abstract for legend
- update fc style title
- replicate change to prod
=> Cleanup legend

dev/services/alchemist/s2_nrt_bs/s2_nrt_bs.alchemist.yaml
Add 3-band burnscar configuration (BSI, dNBR, NDVI).
=> Configuration for 3-band burnscar algorithm.

dev/services/alchemist/ga_s2_wo_3/s2_wo.alchemist.yaml
This PR adds an Alchemist config file for Sentinel 2 definitive WO.
=> Added S2 WO Alchemist config

prod/services/wms/inventory.json, prod/services/wms/ows_refactored/ows_root_cfg.py
=> Release ard

compare-cfg.sh, prod/services/wms/inventory.json, prod/services/wms/ows_refactored/ows_root_cfg.py
- re-attach c3 derivative for release
- fix config parser command
=> attach c3 wo and fc

dev/services/wps/ows/datacube-wps-config.yaml
Config pasted from opendatacube/datacube-wps: datacube-wps-config.yaml
=> Enable WIT in dev WPS

dev/terria/dea-maps-v8.json
Add draft of V8 DEA maps config
=> Add draft of V8 DEA maps config

dev/terria/dea-maps-v8.json
As negotiated with Alicia and Trent, these are the updated DEA Maps catalogue entries.
=> v8 DEA Maps catalogue based on CMI

dev/terria/dea.json
As per advice from Nick Forbes-Smith, WPS elements shouldn't have an opacity fields.
=> Remove opacity from WPS

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/sentinel2/ows_ard_cfg.py
- testing ows layer for newly indexed `s2_ard_granule`
=> testing nbart

workspaces/README.md
=> #777 Initial readme for workspaces

dev/services/wms/ows_refactored/landcover/ows_c2_lc_cyear_cfg.py
- include time resolution
- tidy legends (fix wording, adjust sizes, include image)
=> LC config fix

.env, dev/terria/dea.json
- add tasselcap, nbart_geomad and c3 collection to terria-cube catalog production section.
=> Update terria cube catalog

.github/workflows/terria_linting.yaml, dev/terria/dea-maps-v8.json
- add jsonlint to all json files
- fix v8 json file
=> add lint to all json

dev/terria/dea-maps-v8.json
Update v8 maps with Satellite image changes and C3
Indentation and linting issues have been resolved.
=> Update v8 maps with Satellite image changes and C3

dev/services/wms/ows_refactored/sentinel2/ows_ard_cfg.py, dev/services/wms/ows_refactored/sentinel2/style_s2_cfg.py
Make Sentinel-2 indice names consistent with Collection 3
Make Definitive Sentinel-2 zoom level consistent with NRT
=> Improve Sentinel-2 indice names and zoom

prod/services/wms/inventory.json, prod/services/wms/ows_refactored/c3/style_c3_cfg.py, prod/services/wms/ows_refactored/sentinel2/ows_ard_cfg.py, prod/services/wms/ows_refactored/sentinel2/ows_nrt_cfg.py, prod/services/wms/ows_refactored/sentinel2/style_s2_cfg.py
Sync Dev and Production WMS configs for release of C3 web services and features
- Add Preserve User date order to C3 ARD styling for upcoming release
- Add delta styles to all Sentinel-2 layers
- Add FMask styles to all Sentinel-2 layers
- Made zoom and cache behaviour consistent between NRT and ARD
- Updated Sentinel-2 Layers to have consistent indices names
- Update inventory
=> C3 Web service production release

dev/terria/dea-maps-v8.json
Add available delta styles to upcoming v8 cataloge
=> Add available delta styles to upcoming v8 cataloge

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/ows_root_cfg.py, dev/services/wms/ows_refactored/sentinel2/ows_nrt_provisional_cfg.py, dev/services/wms/ows_refactored/sentinel2/style_s2_cfg.py
- added ows layers
- added them to the root config
- added to inventory
=> sentinel-2 NRT provisional ows configs

dev/terria/terria-cube-v8.json
Add initial draft of terria-cube-v8 catalog
=> Add initial draft of terria-cube-v8 catalog

dev/terria/terria-cube-v8.json
Add WPS and Band math examples to prototype group.
=> Add WPS and Band math examples

dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py
testing the formatting of legend and changing the ndvi colour ramp
=> testing legend and changing ndvi ramp

dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py
Testing legend again, fixing ndbr class layer, and fixing ndvi
=> Burnt area

dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py
fix dnbr class values and minor legend changes
=> fix dnbr class values and minor legend changes

dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py
adding abstract text and trying to fix legends
=> Bunt area v6

dev/terria/terria-cube-v8.json
- Move top-level "baseline" entries down to their sensor-specific folders
- Add provisional products in the "DEA Production" folder
- Change dev IDs so avoid conflict
PS: git diffs of large JSON files with similar entries are awful
=> provisional ARD terria entries reshuffle

dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py
Fix abstract formatting and make minor legend changes
=> Burnt area WMS edits

dev/services/wms/ows_refactored/land_and_vegetation/landcover/lc_class_desc.py, dev/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c2_lc_cyear_cfg.py
Include labels for environmental descriptor layers in feature info
=> lc feature info

dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py
linking legend urls and bolding titles in abstract
=> Final legend edits and formating abstract

products/geomedian-au/ga_ls8c_nbart_gm_cyear_3.yaml
Based on the C3 Geomedian Summary Products Definitions to create the ga_ls8c_nbart_gm_cyear_3 product definition.
=> Add the first ga_ls8c_nbart_gm_cyear_3 product

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
Add TMADs to terria-cube and deamps.
This kind of got lost a year or two ago, but a bunch of work went into it and the web services exist.
=> add tmads to terria-cube and deamaps

dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_s2_cfg.py
Minor updates for consistency after testing layers in dev OWS
=> Consistency update after testing in Dev

products/baseline_satellite_data/README.md, products/inland_water/README.md, products/land_and_vegetation/README.md, products/others/README.md, products/sea_ocean_coast/README.md
based on merged decommission pr #881
=> add readme for all category in products folder

dev/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/ows_landsat_annual_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_nrt_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_nrt_provisional_cfg.py, dev/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py, dev/services/wms/ows_refactored/inland_water/tcw/ows_tcw_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_c3_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_s2_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_alber_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_nov_mar_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_c3_fc_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_fc_albers_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_fc_annual_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_fc_seasonal_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c2_lc_cyear_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/ows_barest_earth_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/ows_mangrove_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/ows_nd_cfg.py, dev/services/wms/ows_refactored/others/aster/ows_aster_cfg.py, dev/services/wms/ows_refactored/others/dev_only/ows_hap_cfg.py, dev/services/wms/ows_refactored/others/ows_mstp_cfg.py, dev/services/wms/ows_refactored/others/ows_weather_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_extents_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_national_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/ows_tide_cfg.py
- remove `default_bands` for `wcs` section
=> update per ows 1.8.20 release

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_summary_cfg.py, dev/terria/terria-cube-v8.json
Add C3 all of time wofs web service for ease of testing.
=> add ga_ls_wo_fq_myear_3 to OWS and terria

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/ows_landsat_annual_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/style_c3_ls_cfg.py, dev/terria/terria-cube-v8.json
Add Ls5 and LS7 GeoMADs to OWS dev and Terria dev
Slight tweak to GeoMAD count style
=> Add ls5 ls7 gm ows terria dev

dev/terria/dea-maps-v8.json
- updated dea maps catalogue document to include ba product. copied material from terria map document
=> Add ba to dea maps catalogue

dev/terria/dea-maps-v8.json
Change Waterbodies on dea maps to point to dea geoserver wms
=> Change Waterbodies to point to dea geoserver wms

dev/services/alchemist/ga_ls_fc_3/ga_ls_fc_c2_3.alchemist.yaml, dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_c2_3.alchemist.yaml, products/inland_water/c3_wo/ga_ls_wo_c2_3.odc-product.yaml, products/land_and_vegetation/c3_fc/ga_ls_fc_c2_3.odc-product.yaml
FC and WO alchemist and product config for testing USGS C2 ARD
=> FC and WO alchemist and product config for testing USGS C2 ARD

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_c3_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_c3_fc_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_fc_cfg.py
add USGS c2 test layers to dev OWS
=> Add USGS C2 test layers

dev/services/wms/inventory.json, prod/services/wms/inventory.json
both files are regenerated by latest cli
=> update inventory json to include layer name

dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_nov_mar_cfg.py
adding "time_resolution": "month" to both seasonal c3 WO to enable meaningful display in Terria and DEA Maps
=> Add time details c3 seasonal wo

dev/terria/terria-cube-v8.json
update terria dev catalogue to include the source data folders/data for c3 wo
=> add wo source data for c3 to terria dev catalogue

prod/services/wms/inventory.json, prod/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/band_c3_ls_cfg.py, prod/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/ows_landsat_annual_cfg.py, prod/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/style_c3_ls_cfg.py, prod/services/wms/ows_refactored/ows_reslim_cfg.py
- deploy c3 geoemdian x3
- deploy wcs config
=> deploy c3 geomedian

dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_annual_cfg.py
add     "time_resolution": "year" to c3 annual water observations. Hopefully will fix bug.
=> add time resolution to annual c3 wo

prod/services/wms/inventory.json, prod/services/wms/ows_refactored/land_and_vegetation/ows_barest_earth_cfg.py, prod/services/wms/ows_refactored/land_and_vegetation/ows_category_root_cfg.py, prod/services/wms/ows_refactored/land_and_vegetation/style_lav_cfg.py
Updated production LAV config with S2 barest earth
=> Release S2 Barest Earth to production OWS

dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_cfg.py, dev/terria/terria-cube-v8.json
fixing catalogue issues and naming conventions
=> bug fixes to last wos pr

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_nov_mar_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py, dev/terria/terria-cube-v8.json
adding WO style from DE Africa, removing subfolders from c2, fixing inventory and catalogue bugs.
=> Add colour vision friendly WO style and fix bugs

dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py, dev/terria/terria-cube-v8.json
minor edits and hoping that terria issues are associated with year format in catalogue file.
=> test year format for terria

dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_c3_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py, dev/terria/terria-cube-v8.json
It looks like all of the layers are fine in ows. But the Terria catalogue is bugging out on the individual observation, and both seasonal layers, showing no information what-so-ever. 
Additionally, the calendar year layer shows data when you click on a point, but no visualisation. 
I have no idea if these changes will actually fix.
=> continue to bug fix

dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_alber_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_nov_mar_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_c3_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py, dev/terria/terria-cube-v8.json
I'm not sure why the ows and terria wms is not working. I think it may be associated with time resolution and date format
=> trying to get nov seasonal stats to work

dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py
hopefully last pr to fix seasonal wo bug
=> Fix wo error

dev/services/wms/ows_refactored/inland_water/wofs/annual/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_c3_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/multiyear/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/seasonal/ows_wofs_nov_mar_cfg.py, dev/terria/terria-cube-v8.json
update the abstract text and titles for each WO product. Text from CMI.
=> Standardise WO product text and titles

dev/services/wms/ows_refactored/ows_reslim_cfg.py
Minor tweak.  LCCS was still a bit slow when it first cuts over to imagery.
=> Increase minimum zoom for LCCS.

prod/services/wms/ows_refactored/others/ows_mstp_cfg.py, prod/services/wms/ows_refactored/ows_reslim_cfg.py
Working much nicer in dev now.
=> Promote MSTP reslim adjustment to prod

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
attempting to add C3 WO products into DEA Maps catalogue.
=> update DEA Maps catalogue WO

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
Reverts GeoscienceAustralia/dea-config#1029
=> Revert "update DEA Maps catalogue WO"

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
fix deprecated labels and add C3 WOs to DEA Maps
=> Update dea maps to include C3 WOs

dev/terria/terria-cube-v8.json
Updating the Terria catalogue to reflect the v1 and v2
=> Update catalogue to reflect Waterbodies v1 and v2

dev/terria/dea-maps-v8.json
Point DEA Maps to the non-prod waterbodies webservices while the prod services are being updated
=> Update Waterbodies on dea maps

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
Switching Waterbodies catalogue item to point to the newly updated wms on the dea prod geoserver.
Also, changing Waterbodies on terria and dea maps to use a png for the legend.
=> Waterbodies v2

prod/services/alchemist/ga_ls_fc_3/ga_ls8_fc_3.alchemist.yaml
- remove ls8 from old config, not necessary, but for clarity
- add new config for ls8, with new coefficients and updated version `2.5.1`
=> change fc config for reprocessing

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_alber_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_annual_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_apr_oct_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_nov_mar_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_summary_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_cfg.py, dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_provisional_3.py, dev/services/wms/ows_refactored/inland_water/wofs/ows_wofs_cfg.py, dev/terria/terria-cube-v8.json, prod/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_alber_cfg.py, prod/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_annual_cfg.py, prod/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_apr_oct_cfg.py, prod/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_nov_mar_cfg.py, prod/services/wms/ows_refactored/inland_water/wofs/c2/ows_wofs_summary_cfg.py
- adding "ga s2 wo provisional 3" to ows and terria catalogue. 
- add "deprecated" to old WO that is based on old S2 input data.
- replace "depricated" with "deprecated"
=> Add ga s2 wo provisional 3

dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_provisional_3.py, dev/terria/terria-cube-v8.json
1) corrected product name in ows file
2) made ID in Terria catalogue unique
=> fix s2 WO ows and terria bug

dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_cyear_3.yaml, dev/services/odc-stats/fc_percentile/ga_ls_fc_pc_fyear_3.yaml
Update fc percentile version to be consistent with product definition.
=> update fc percentile version

dev/services/odc-stats/tc_percentile/ga_ls_tc_pc_cyear_3.yaml, products/inland_water/c3_tc/ga_ls_tc_pc_cyear_3.yaml
Sample datasets produced here if you wonder what it looks like by this config
http://dea-public-data-dev.s3-website-ap-southeast-2.amazonaws.com/?prefix=test/tc-everything/x08/y25/2015--P1Y/
=> add all bands to tci

.github/.codecov.yml, .github/workflows/coverage.yaml, .github/workflows/ows_cfg_testing_dev.yaml, .github/workflows/ows_cfg_testing_prod.yaml, README.md, compare-cfg.sh, docker-compose.ows.yaml
- simplify `docker-compose.ows.yaml` for cfg testing
- include `prod` cfg in coverage test
=> simplify docker-compose mnt

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
following from #1050 , this is to remove corresponding layer from catalog
=> remove c2 decommissioned layers from catalog

dev/services/wms/ows_refactored/land_and_vegetation/fc/ows_c3_fcp_cfg.py, dev/services/wms/ows_refactored/land_and_vegetation/fc/style_fc_cfg.py, dev/terria/terria-cube-v8.json
- move `fc rgb` style to top of the list so its loaded as default layer
- add `fcp cyear` to terria catalog
=> add fcp cyear to catelog

dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_apr_oct_3.yaml, dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_cyear_3.yaml, dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_fyear_3.yaml, dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_myear_3.yaml, dev/services/odc-stats/wofs_summary/ga_ls_wo_fq_nov_mar_3.yaml
=> collect pre-defined config in the config files

dev/services/odc-stats/geomedian/ga_ls7e_nbart_gm_cyear_3.yaml
Needed for Argo 2021 geomedian summary product run
=> Add ls7e gm config

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/ows_category_root_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_c3_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_s2_cfg.py
This still requires a CMI link and updates to abstract descriptions. Setting up testing initial configurations.
=> Add draft ga_s2m_ard_3 layer in dev terria

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/band_s2_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/style_s2_cfg.py
Add basic `color_ramp` layer for `s2cloudless_prob`
=> Add s2cloudless_prob

.github/workflows/ows_linting.yaml, dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/style_s2_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/utils.py
Some experimental visualisations of S2C3 cloud probability in dev.
Visualising cloud probability as transparency, and as darkness.
=> Cloud probability as transparency and darkness styles.

.github/workflows/docker-image.yml
fix for https://github.com/GeoscienceAustralia/dea-config/actions/runs/3373835301/jobs/5598800898
=> fix docker lint

products/land_and_vegetation/lccs/ga_ls_landcover_class_fyear_3.odc-product.yaml
We plan to index the `ga_ls_landcover_class_fyear_3`, then we upload its product cfg file.
=> Upload the LCCS FY proudct cfg

dev/services/alchemist/s2_nrt_wo/s2_c3_nrt_wo_provisional.alchemist.yaml
switch products in the alchemist product specification
=> switch to new s2 c3 nrt product

prod/services/alchemist/ga_s2_ba_3/s2_c3_nrt_ba_provisional.alchemist.yaml
upgrade burnt area to latest Sentinel 2 NRT input
=> upgrade burnt area s2 c3

prod/services/alchemist/ga_s2_ba_3/s2_c3_nrt_ba_provisional.alchemist.yaml
getting below error:
[error    ] Failed to run transform datacube_alchemist.transforms.DeltaNBR_3band_s2be on dataset 190e59f6-ac51-4010-98bf-b7fa3182affa with error Need more properties to fulfill naming conventions.
- 'dea:dataset_maturity'
=> add dataset maturity back in

dev/services/wms/ows_refactored/ows_reslim_cfg.py, dev/services/wms/ows_refactored/ows_root_cfg.py, prod/services/wms/ows_refactored/ows_root_cfg.py
I messed up and edited the Prod OWS config instead of the Dev OWS config in #1138
=> Actually change OWS Dev config for caching

prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/style_combined_cfg.py
=> Fix typo - only two m's in common!

dev/terria/dea-maps-v8.json, dev/terria/terria-cube-v8.json
This PR adds the combined Landsat and S2 OWS layer to DEA Maps.
=> Add OWS combined LS S2 layer to DEA Maps

prod/services/alchemist/ga_s2_wo_3/s2_c3_nrt_wo_provisional.alchemist.yaml
adding alchemist config for s2 wo nrt in prod
=> alchemist config s2 wo nrt

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/ows_category_root_cfg.py
New latest-imagery timeless mosaic layer (in dev).  
Uses the new `mosaic_date_func` OWS feature that will be released in v1.8.34.
=> Timeless mosaic layer of latest LS/S2 imagery.

dev/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_provisional_3.py, dev/terria/terria-cube-v8.json, prod/services/wms/inventory.json, prod/services/wms/ows_refactored/inland_water/wofs/individual/ows_s2_wo_provisional_3.py, prod/services/wms/ows_refactored/inland_water/wofs/ows_wofs_cfg.py, products/inland_water/s2_wo/ga_s2_nrt_c3_wo.odc-product.yaml
Adding new web service in production, and adding it to production section in terria cube for initial testing.
=> ga-s2-wo-3 add ows and into terria-cube

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/hazards/burntarea/ows_ls_burncube_cfg.py, dev/services/wms/ows_refactored/hazards/ows_category_root_cfg.py, products/hazards/burntarea/ga_ls_nbart_bc_fyear_3_demo.odc-product.yaml
Adding burncube burnt area product to dev ows catalogue following https://docs.dev.dea.ga.gov.au/procedures/develop_ows_layer.html#develop-ows-layer instructions.
Wording (e.g. abstract) are not complete, but are just first draft to see how displays on ows.
=> adding burncube to ows

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/hazards/burntarea/ows_ls_burncube_cfg.py, dev/terria/terria-cube-v8.json
This is a draft to test terria catalogue and combining measurements from same product into one style.
=> adding bc to dev terria catalogue and combining bc style

dev/services/wms/ows_refactored/hazards/burntarea/ows_ls_burncube_cfg.py, dev/terria/terria-cube-v8.json
Add text to OWS abstract
link to BurnCube combined legend
Fix typos
=> Update dev BurnCube OWS and Terria catalogue

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal/ows_national_cfg.py
This PR adds two additional styles to the DEA Intertidal layers on dev OWS, so we can see if this will be a useful solution to the issue of highly divergent elevation ranges in micro and macrotidal locations.
=> Add test of micro and macrotidal DEA Elevation styles

dev/terria/terria-cube-v8.json, prod/terria/dea-maps-v8.json
=> Fix Landsat typo

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/hazards/burntarea/ows_ls_burncube_cfg.py, dev/terria/terria-cube-v8.json
We have just indexed the latest version of burncube to odc. I have updated the ows, and terria catalogue to point at new product + minor wording edit.
=> update burncube ows to new product

dev/terria/terria-cube-v8.json
=> add other BC to Terria catalogue

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/hazards/historic_burn/ows_category_historic_cfg.py, dev/services/wms/ows_refactored/hazards/historic_burn/ows_s2_burncube_fyear_cfg.py, dev/terria/terria-cube-v8.json
@erin-telfer, added config file for burncube sentinel-2 financial year. Updated inventory file and count, as well as terria catalogue.
=> adding ows for burncube sentinel-2 fyear

dev/services/wms/ows_refactored/hazards/nrt_burn/ows_provisional_ba_cfg.py, dev/terria/terria-cube-v8.json, prod/services/wms/ows_refactored/hazards/burntarea/ows_provisional_ba_cfg.py, prod/terria/dea-maps-v8.json
Deprecate the Sentinel 2 Collection 3 NRT Burnt Area Product as CCB No: 20230809.1
Includes:
- removal from DEA Maps
- renaming product in ows and adding note to abstract
- renaming product in Terria
=> Deprecate BA product

dev/terria/terria-cube-v8.json, prod/terria/dea-maps-v8.json
Update "8" to "9" in product name as per advice from Arek
=> Fix broken Himawari mosaic layer

dev/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py, prod/services/wms/ows_refactored/baseline_satellite_data/landsat/ows_c3_cfg.py, prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py
Update the abstract links for LS9
=> update LS9 link

dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
Add missing tide attribute bands required for calculating adaptive style.
=> Fix DEA Intertidal adaptive elevation style

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/ows_intertidal_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
This PR:
- Updates the lower colour limit in the adaptive uncertainty style to avoid completely black pixels
- Reorders the styles to put the adaptive style up to (and set to default)
- Adds a draft abstract
=> Update styling, reorder styles, add abstract

dev/terria/terria-cube-v8.json
=> Update DEA Intertidal date format

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/ows_intertidal_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py
Adds NDWI corr and freq bands to Terriacube (we don't have to add them to the version we publish on prod)
=> Add QA layers to DEA Intertidal

prod/services/alchemist/ga_ls_fc_3/ga_ls8_ls9_fc_3.alchemist.yaml
Upgrade Alchemist configuration to include Landsat-9.
=> Update Alchemist configuration to include LS-9.

dev/terria/terria-cube-v8.json
Update folder name to explicitly state GeoMAD
=> rename folder name catalogue

dev/terria/terria-cube-v8.json, prod/terria/dea-maps-v8.json
Add Prod GeoMAD to terria and dea maps
=> Add Prod GeoMAD to terria and dea maps

dev/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/band_ls_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_annual/style_ls_cfg.py
These two configs appear to still be used by other web services, adding them back in for now
=> Geomad decom dev 2

dev/services/odc-stats/lccs/ga_ls5_landcover_inter_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls7_landcover_inter_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls8ls9_landcover_inter_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_artificial_surface_cyear_3.yaml
=> landcover config to differentiate aquatic veg in level 1

dev/services/odc-stats/lccs/ga_ls5_landcover_inter_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls7_landcover_inter_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls8ls9_landcover_inter_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_artificial_surface_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_class_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_cultivated_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_nidem_myear_2.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_vwf_cyear_3.yaml, dev/services/odc-stats/lccs/ga_ls_landcover_woody_cyear_3.yaml, dev/services/odc-stats/lccs/srtm_landcover_dem.yaml, prod/services/odc-stats/lccs/ga_ls5_landcover_inter_class_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls7_landcover_inter_class_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls8ls9_landcover_inter_class_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls_landcover_artificial_surface_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls_landcover_class_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls_landcover_cultivated_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls_landcover_nidem_myear_2.yaml, prod/services/odc-stats/lccs/ga_ls_landcover_vwf_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls_landcover_woody_cyear_3.yaml, prod/services/odc-stats/lccs/srtm_landcover_dem.yaml
Configurations for when we go into production
=> Land Cover Processing Configurations

dev/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c3_lc_cyear_cfg.py, prod/services/odc-stats/lccs/ga_ls5_landcover_inter_class_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls7_landcover_inter_class_cyear_3.yaml, prod/services/odc-stats/lccs/ga_ls8ls9_landcover_inter_class_cyear_3.yaml
Fix OWS bugs and update processing config with mangroves input from ODC
=> Update landcover ows

.github/workflows/docker-image.yml, .github/workflows/ows_cfg_testing_dev.yaml, docker-compose.ows.yaml, prod/services/wms/inventory.json
The failure caused by the db connection is fixed. The sanity check on own layers failed, the number of layers should match the actual number in the list.
=> Fix git action failure

product_metadata/eo3_landsat_ard.odc-type.yaml, product_metadata/eo3_sentinel_ard.odc-type.yaml, products/baseline_satellite_data/c3/esa_s2cm_level1_0.odc-product.yaml
... and add a `final_ancillaries` field to Landsat to match our Sentinel ARD.
=> Add S2C L1 definition

dev/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c3_lc_cyear_cfg.py
=> update lc legend

dev/services/wms/ows_refactored/land_and_vegetation/landcover/ows_c3_lc_cyear_cfg.py
Add note around GQA fix in ows
=> update ows gqa

prod/terria/dea-maps-v8.json
Do not merge until approved by Leyla, and the other PR is deployed first re OWS deployment
=> Add Landcover OWS to DEA Maps

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py, dev/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_s2_cfg.py
Added Sentinel-2C to our dev OWS to see if it works
=> Add Sentinel-2C to OWS

dev/terria/terria-cube-v8.json, prod/services/wms/inventory.json, prod/services/wms/ows_refactored/baseline_satellite_data/landsat_s2_combined/ows_c3_cfg.py, prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_ard_cfg.py, prod/services/wms/ows_refactored/baseline_satellite_data/sentinel2/ows_s2_cfg.py
Copy of #1320 for prod OWS.
Also adds Sentinel-2C layer to dev Terria map; will add to DEA Maps once the data is available in prod OWS
=> Add S2C to prod OWS, dev Terria

dev/services/wms/ows_refactored/hazards/burn_mapping_uplift/ows_burncube_cfg.py, dev/services/wms/ows_refactored/hazards/burn_mapping_uplift/ows_dea_gbdt_cfg.py, dev/services/wms/ows_refactored/hazards/burn_mapping_uplift/ows_rbr_cfg.py, dev/services/wms/ows_refactored/hazards/burn_mapping_uplift/ows_stacking_uncertainty_cfg.py, dev/services/wms/ows_refactored/hazards/dea_fmc/ows_fmc_cfg.py, dev/terria/terria-cube-v8.json
this update makes changes to hazard products in development
=> Hazards updates

dev/services/wms/inventory.json, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/ows_intertidal_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/style_intertidal_cfg.py, dev/services/wms/ows_refactored/sea_ocean_coast/intertidal_c3/utils_intertidal.py
Adds Extents style
Fixes broken tide graph links and metadata
=> Add Extents layer to DEA Intertidal, fix tide graph

dev/terria/terria-cube-v8.json, prod/services/wms/inventory.json, prod/services/wms/ows_refactored/hazards/dea_fmc/ows_fmc_combined_cfg.py
new fmc goes on terria for testing
=> put fmc on terria
